### ISSUE TITLE
replicate doesn't rehash the tree

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#145]

**Comment by sg-s** [comment]
apparently this is expected behavior inherited from `cpplab` --- there needs to be a warning about this somewhere in the documentation

**Comment by alec-hoyland** [comment]
Is this something that x.md5hash at the end of replicate would fix? 

e.g.

```matlab
if ~x.skip_hash
  x.md5hash
end
```

or is this a more significant quirk?

**Comment by sg-s** [comment]
you're right -- will fix in `cpplab`
