### ISSUE TITLE
new feature: snapshot() and enhancements to reset()

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#159]
# the idea:

introduce `snapshot('somestring')` which will save the state of the xolotl object using `x.serialize` 

we can then quickly go back to it using `x.reset('somestring')`

**Comment by alec-hoyland** [comment]
oh that's cool, so you can actually return to a hashed state.

**Comment by sg-s** [comment]
it's not a hashed state, it's more of a "saved" state. the idea is you can "save" any number of points, and flip back to them whenever you want to
