### ISSUE TITLE
all the Calcium channels added recently are wrong

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#166]
Calcium channels should update `i_Ca`, otherwise they don't change `Ca` inside the compartment. 

see, e.g., [this line](https://github.com/sg-s/xolotl/blob/e884375339bff5811bf54e3151b5250cebacd3cb/c%2B%2B/conductances/prinz/CaS.hpp#L55)

**Comment by alec-hoyland** [comment]
Fixed
