### ISSUE TITLE
cpplab.add() and xolotl.add() do not have the same syntax w.r.t naming objects

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#167]
# the way it works now

* `x.add('AB','compartment',...)`
* `x.AB.add('object','name',...)`

# the way it should work

`something.add('object','name',...')`

**Comment by alec-hoyland** [comment]
So the major change is that adding compartments is now going to have
arguments in the correct order? e.g.

`x.add('compartment', 'AB', ...)`
`x.AB.add('liu/NaV', ...)`

**Comment by sg-s** [comment]
yeah...the first argument is the type of object, second is the name you want to give it (optional), and so on

**Comment by alec-hoyland** [comment]
I think this is a necessary change. Better now than far in the future.

**Comment by sg-s** [comment]
OK, check out the 167 branch and see if everything works. if so, I'll merge. 

You'll need to pull from cpplab too

**Comment by alec-hoyland** [comment]
Works for me on Manjaro 17

**Comment by sg-s** [comment]
OK, will merge.

**Comment by sg-s** [comment]
cpplab does not show this behaviour. there is now a mismatch between this and x.add()

**Comment by sg-s** [comment]
should be the same now

**Comment by alec-hoyland** [comment]
Works for me, Arch Linux Manjaro 18
