### ISSUE TITLE
compiler woes on Ubuntu

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#191]
# Bug reports

 ### information on OS, MATLAB version, ``xolotl`` version

Ubuntu 18.04

Failure to compile. 

errors:

```
*** Compilation failed:
/usr/bin/x86_64-linux-gnu-ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
 ```

this is a generic error because `GetMD5` didn't compile -- the issue is with the MATLAB/mex compiler

**Comment by luadam4c** [comment]
This error occurs while running GetMD5

**Comment by sg-s** [comment]
OK, that means your mex compiler doesn't work at all. @alec-hoyland used Ubuntu 18.04 LTS and I remember he had quite a bit of trouble getting mex to work, but it does work! I'll try to figure out what he did.

**Comment by luadam4c** [comment]
mex.getCompilerConfigurations('c')

ans = 

  CompilerConfiguration with properties:

             Name: 'gcc'
     Manufacturer: 'GNU'
         Language: 'C'
          Version: ''
         Location: '/usr/bin/gcc'
        ShortName: 'gcc'
         Priority: 'A'
          Details: [1×1 mex.CompilerConfigurationDetails]
       LinkerName: ''
    LinkerVersion: ''
           MexOpt: '/home/adam/.matlab/R2018a/mex_C_glnxa64.xml'

**Comment by luadam4c** [comment]
My gcc was already v7.3.0:

`gcc --version`

> gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by sg-s** [comment]
hmm .. can you try 

```
!g++ --version
```

from matlab? I want to make sure MATLAB sees the same version that your shell does

**Comment by sg-s** [comment]
@alec-hoyland had this wisdom to share when he faced this issue on 18.04:

The issue seems to be the fact that the mex -setup command is absolute shit. Mathworks doesn't say it's deprecated, but I can't find anyone other than them who encourages its use. Also, the mexopts.sh file in your MATLAB installation seems totally useless.

"MATLAB supports only one compiler for each language on Linux® platforms. If you have multiple compilers installed, the default compiler might not be the MATLAB-supported compiler. You can either change the system default compiler for all applications, or select the MATLAB-supported compiler each time you run the mex command."

For example, I can write a C file that prints "Hello, world!" and compile it with mex.

>> mex test.c
Building with 'gcc'.
MEX completed successfully.
>> test
Hello, World!
I have 0 inputs and 0 outputs
>> !which gcc
/bin/gcc
>> !gcc -dumpversion
8.1.0
>> mex -setup c
MEX configured to use 'gcc' for C language compilation.

If I try to do the same thing with a .cpp file...

>> !which g++
/bin/g++
>> !g++ -dumpversion
8.1.0
>> mex test.cpp
Error using mex
No supported compiler was found. For options, visit https://www.mathworks.com/support/compilers.

And this is because...

mex -setup C++
Error using mex
No supported compiler was found.

There are a lot of fixes on Stack Exchange and none of them work. Turns out, MATLAB doesn't create the proper xml file for C++! I have no idea why it doesn't do that, but it doesn't.

The fix is as follows:

1. Download the proper version of gcc/g++. The AUR has versions 4.9, 5.5, and 6.4 as legacy builds.

2. Change the ~/.matlab/R2018a/mex_C_glnxa64.xml file to reflect the version of gcc you want. This involves replacing all references to $GCC with the path to the soft link, e.g. /usr/bin/gcc-6. Credit goes to this guy for figuring it out: https://gist.github.com/bonanza123/bb38a9a95e450e2bc99a6ac8d8513cf2.

3. Do the same to the ./mex_C++_glnxa64.xml file, but replace references to the C compiler with g++.  If the file doesn't exist, copy the C-specific xml file and rename the copy. MATLAB will figure it out...again, I don't know why this file doesn't exist in the first place. 

You want to get something like this

>> mex.getCompilerConfigurations('C++')

ans = 

  CompilerConfiguration with properties:

             Name: 'g++'
     Manufacturer: 'GNU'
         Language: 'C++'
          Version: ''
         Location: '/usr/bin/g++-6'
        ShortName: 'g++'
         Priority: 'A'
          Details: [1×1 mex.CompilerConfigurationDetails]
       LinkerName: ''
    LinkerVersion: ''
           MexOpt: '/home/alec/.matlab/R2018a/mex_C++_glnxa64.xml'

**Comment by luadam4c** [comment]
```MATLAB
!g++ --version
```

> g++ (crosstool-NG fa8859cb) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```MATLAB
!gcc --version
```

> gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by sg-s** [comment]
the biggest red flag i see is that you're using the version that's bundled with Anaconda, instead of the system one. I would change that to point to your system `g++`

```
edit(mex.getCompilerConfigurations('C++').MexOpt)
```

you can use a C++ compiler for C

**Comment by luadam4c** [comment]
So apparently Ubuntu 18.04 LTS doesn't come with the g++ library installed. Perhaps you can add this to your instructions:
```bash
sudo apt-get install g++
```

After doing that, MATLAB was able to find the installed g++ library when I do this in MATLAB (probably because I had the Anaconda path listed *after* the system paths):
```MATLAB
mex -setup C++
```

This is verified with the following:
```MATLAB
mex.getCompilerConfigurations('C++')
```

> ans = 
> 
>   CompilerConfiguration with properties:

             Name: 'g++'
     Manufacturer: 'GNU'
         Language: 'C++'
          Version: ''
         Location: '/usr/bin/g++'
        ShortName: 'g++'
         Priority: 'A'
          Details: [1×1 mex.CompilerConfigurationDetails]
       LinkerName: '/usr/bin/g++'
    LinkerVersion: ''
           MexOpt: '/home/adam/.matlab/R2018a/mex_C++_glnxa64.xml'

And now GetMD5 works!

**Comment by sg-s** [comment]
great! did you try running of the examples in `xolotl/tests`?

**Comment by luadam4c** [comment]
I just did and all the tests were passed. This was true with a fresh install using git into a different folder from the home directory too.

Thanks a lot!

**Comment by sg-s** [comment]
awesome!
