### ISSUE TITLE
`add` should clear out every saved snapshot

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#201]

**Comment by sg-s** [comment]
this is actually very hard to do -- how does one trigger a clearing of the snapshots if something is added to a compartment/conductance?

**Comment by sg-s** [comment]
one way is to associate every snapshot with the hash of the model, and silently ignore/delete snapshots with hashes that don't match the current model

**Comment by alec-hoyland** [comment]
If you can check what the type of the object calling the `add` function is, then you can delete the snapshots by just removing all of them at the same time you add (i.e. in the `add` function). Are there any conditions in which the `add` function would _not_ want to erase every snapshot for a certain object?

**Comment by sg-s** [comment]
but the problem is that `add` is a cpplab method. 

yes, it's also an overloaded method in xolotl, but that's only for adding compartments. 

we need to make sure snapshots are destroyed when a new channel is added to a compartment, e.g.

**Comment by sg-s** [comment]
Another way to fix this is to associate every snapshot with a hash of the model, so that invalid snapshots are automatically excluded
