### ISSUE TITLE
Replicate doesn't recursively replicate properties set by anonymous functions

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#208]
Not sure if this is a feature or a bug; also not sure if it's even reasonably fixable.

How to reproduce:

1. Make a neuron with a property set by an anonymous function
```matlab
vol = 0.0628; % this can be anything, doesn't matter
f = 1.496; % uM/nA
tau_Ca = 200;
F = 96485; % Faraday constant in SI units
phi = (2*f*F*vol)/tau_Ca;

x = xolotl;
x.add('compartment','AB','Cm',10,'A',0.0628,'vol',vol,'phi',phi,'Ca_out',3000,'Ca_in',0.05,'tau_Ca',tau_Ca);

x.AB.add('liu/NaV','gbar',@() 115/x.AB.A,'E',30);
x.AB.add('liu/CaT','gbar',@() 1.44/x.AB.A,'E',30);
x.AB.add('liu/CaS','gbar',@() 1.7/x.AB.A,'E',30);
x.AB.add('liu/ACurrent','gbar',@() 15.45/x.AB.A,'E',-80);
x.AB.add('liu/KCa','gbar',@() 61.54/x.AB.A,'E',-80);
x.AB.add('liu/Kd','gbar',@() 38.31/x.AB.A,'E',-80);
x.AB.add('liu/HCurrent','gbar',@() .6343/x.AB.A,'E',-20);
x.AB.add('Leak','gbar',@() 0.0622/x.AB.A,'E',-50);

x.t_end = 1e4;
x.integrate;
x.t_end = 1e3;
```
2. Replicate that neuron
```matlab
x.replicate('AB', 2)
x.connect('AB', 'AB2', 100)
```

3. Observe that the maximal conductances of `AB2` are defined as functions of a property of `AB`
```matlab
+ AB  
  > ACurrent (g=15.45/x.AB.A, E=-80)
  > CaS (g=1.7/x.AB.A, E=79)
  > CaT (g=1.44/x.AB.A, E=79)
  > HCurrent (g=.6343/x.AB.A, E=-20)
  > KCa (g=61.54/x.AB.A, E=-80)
  > Kd (g=38.31/x.AB.A, E=-80)
  > Leak (g=0.0622/x.AB.A, E=-50)
  > NaV (g=115/x.AB.A, E=30)
---------------------
+ AB2  
  > ACurrent (g=15.45/x.AB.A, E=-80)
  > CaS (g=1.7/x.AB.A, E=79)
  > CaT (g=1.44/x.AB.A, E=79)
  > HCurrent (g=.6343/x.AB.A, E=-20)
  > KCa (g=61.54/x.AB.A, E=-80)
  > Kd (g=38.31/x.AB.A, E=-80)
  > Leak (g=0.0622/x.AB.A, E=-50)
  > NaV (g=115/x.AB.A, E=30)
```

**Comment by sg-s** [comment]
yes, this is expected behaviour. i'm going to leave this open since this is non-ideal, but I have no plans to fix this (i don't even know if it can be fixed)

**Comment by alec-hoyland** [comment]
It would involve reading through each property to make sure that none are defined by anonymous functions, then reading the function as a string to parse for any properties referenced, then modify those properties in-place. Alternatively, you could add (yet another) flag that points to that property...

It's probably better to just understand that this is a pretty rare scenario that could be avoided by a loop that assigns the properties by the user.

**Comment by sg-s** [comment]
yeah, this is an issue with cpplab.

**Comment by sg-s** [comment]
This will be closed because this is expected behavior.
