### ISSUE TITLE
delete all conductance integration methods in specific channel files

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#227]
because `conductance.integrate()` now works, and `p` and `q` specify exponents of channels

**Comment by sg-s** [comment]
@alec-hoyland want to take a crack at this? i've done most of them...

**Comment by alec-hoyland** [comment]
Will do

⁣Get BlueMail for Android ​

**Comment by alec-hoyland** [comment]
Is there any extant purpose for the`liu-euler` folder?

**Comment by sg-s** [comment]
should probably nuke it

**Comment by sg-s** [comment]
fixed?

**Comment by alec-hoyland** [comment]
Yes, I think this is taken care of.
