### ISSUE TITLE
consider offering a installation from a PPA or as a .deb package

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#239]

**Comment by alec-hoyland** [comment]
I've been thinking about this. Wrote up a preliminary script to put together the folder needed for a Debian package. Xolotl is really lightweight -- it doesn't need `make` or anything, so I also put together a simple script that just grabs the repositories and fixes the MATLAB path.

**Comment by sg-s** [comment]
nice--how does one fix the matlab path from outside matlab though?

**Comment by alec-hoyland** [comment]
There are two ways to do that. Either (a) edit the pathdef.m file directly or (b) call matlab from the command line.

```bash
 matlab -nodisplay -nodesktop -r "addpath('$pwd/cpplab', '$pwd/xolotl', '$pwd/puppeteer', genpath('$pwd/srinivas.gs_mtools/src'); quit;"
```
