### ISSUE TITLE
Methods are out of order in documentation

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#250]
In the [methods](https://xolotl.readthedocs.io/en/latest/auto_methods.html) tab, the methods are not listed in alphabetical order or anything else of that ilk.

**Comment by sg-s** [comment]
yes....why? [this](https://github.com/sg-s/xolotl/blob/5d9680de8fb9e053d635082575ef537a7fc1b85c/make_docs.py#L14) is the problem

**Comment by alec-hoyland** [comment]
I *think* this will do it

```python
sorted(glob.glob("@xolotl/*.m"))
```

**Comment by alec-hoyland** [comment]
Here is a more complicated explanation
https://stackoverflow.com/questions/6773584/how-is-pythons-glob-glob-ordered

The short answer is `glob.glob()` calls `os.listdir()` which is basically just `ls -U`

**Comment by sg-s** [comment]
damn you python

**Comment by sg-s** [comment]
fixed
