### ISSUE TITLE
Consistency in Flags

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#255]
Is there any reason why `verbosity` is a double but `closed_loop` is a logical? Is there a difference? Should they both be one way?

**Comment by alec-hoyland** [comment]
In the case of the `approx_channels` flag, what then? It has to be of type double in MATLAB. Does it make sense to write a `set` function for `closed_loop` that converts doubles to logicals? Or does it make more sense to just make everything that can be logical just doubles?

**Comment by sg-s** [comment]
> In the case of the approx_channels flag, what then? It has to be of type double in MATLAB

no, cpplab requires `approx_channels` to be double, because every parameter in a cpplab object has to be double

> Does it make sense to write a set function for closed_loop that converts doubles to logicals?

will do this.

**Comment by sg-s** [comment]
OK, fixed see [this](https://github.com/sg-s/xolotl/blob/9d5a2d6a1f3e6b76c58633b75dc1a7bd1fb08192/%40xolotl/xolotl.m#L152)

Now, the behaviour is as follows:

```
* x.closed_loop = true; % OK
* x.closed_loop = false; % OK
* x.closed_loop = 0; % OK, interpreted as false
* x.closed_loop = 1; % OK, interpreted as true
* x.closed_loop = 'true'; % error
* x.closed_loop = 'F'; % interpreted as true
```

**Comment by alec-hoyland** [comment]
I think this is good.

**Comment by luadam4c** [comment]
`x.closed_loop = 0;` doesn't work for me. I get this error:

> Error setting property 'closed_loop' of class 'xolotl':
Value must be 'logical'.
> 
> Error in cpplab/subsasgn (line 36)
self = builtin('subsasgn',self,S,value);
