### ISSUE TITLE
Figure out math formatting with RTD

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#265]

**Comment by sg-s** [comment]
from what i understand about RTD and mkdocs, RTD allows you to create a whole new python virtualenv for your build. so it's possible to do anything you want and use and python code you want. all the python code to convert markup to latex exists in our repo "setup.py" and "mdx_math.py" 

but what i don't know how to do is to get these files to be run when the build is triggered.

**Comment by sg-s** [comment]
fixed! go wild with latex, inline supported as well.
