### ISSUE TITLE
proposal for major breaking change in architecture

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#275]
# the problem:

* synapses are a vector of cpplab objects, while nothing else is a vector
* synapses are contained by the xolotl object, but are not created using `add`
* synapses appear as Children of xolotl objects, but were not created using `add`

This means that hashing tied to `add` misses the synapses, which is why we have a kludge where the entire tree is rehashed if we have synapses. This is very wasteful. 

# potential solutions: 

in the new cpplab architecture (`no-children` branch ), we have solved this wasteful hashing problem. but since `synapses` don't show up in `x.Children`, everything is broken. 

what if we gave up on the `synapses` as a vector of cpplab object? every synapse would then be contained by the post-synaptic compartment. this would require no change in the C++ code, but would require massive changes in the middleware layer (`transpileCore`) and would make it reasonable to remove all support for vector objects from `cpplab`

**Comment by sg-s** [comment]
works in branch.

also uses the new cpplab architecture, which confers the following advantages:

* can remove objects from the tree!
* `md5hash` is gone. that's because hashing is now optimized, and everything is automatically hashed, always.

**Comment by alec-hoyland** [comment]
All tests passed on Arch Linux, MATLAB 9.4.0.813654 (R2018a). GCC version 8.1.

**Comment by alec-hoyland** [comment]
This is a MUCH better architecture, I'm very happy with it.
