### ISSUE TITLE
Reorganize mechanisms by author/year

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#279]
This is something we thought about doing a while ago (still in PR #219).
So, instead of `CalciumMech1` we would have `prinz/CalciumMech` or something of that ilk.

This would be slightly breaking, since all extant code using calcium mechanisms would have to update their mechanism search signature, but that should be very easy to rectify.

**Comment by sg-s** [comment]
we should probably do this

**Comment by sg-s** [comment]
fixed
