### ISSUE TITLE
another breaking change

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#281]
synapses will not contain a gbar field, only conductances will do so

the reason is because now synapses are mixed up with conductances inside a single compartment, so it makes it hard to pull out just the channel conductances.

secondly, they have different units: the synapse is in nS, while the gbars are in uS/mm^2. in fact, the bar in gbar refers to the "specific" nature.

**Comment by sg-s** [comment]
gbar -> gmax

**Comment by alec-hoyland** [comment]
Seems reasonable to me
