### ISSUE TITLE
questions that need to be answered somewhere in the documentation

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#290]
a real world user had these questions:

1. For a multi-compartment model, do I just connect compartments with electrical synapses? Is that mathematically equivalent with the discretization of the cable equation? If so, how do I convert axial resistivity to the gbar for the electrical synapse, or can the axial resistivity be set somewhere?
2. For a multi-compartment model, how can I be sure that the surface area is computed without including the ending disks? Is it possible to make the A and V parameters update automatically whenever radius and diameter is set? Right now it seems like it is just showing default values. I know it might be ignored in calculations based on your documentation, but it's a little confusing.

**Comment by alec-hoyland** [comment]
These are good questions. See PR #291 for my attempt.
