### ISSUE TITLE
Temperature units

### ISSUE THREAD

**Issue by luadam4c** [sg-s/xolotl#295]
The units for temperature listed here is K, but the default temperature_ref is 11.

Are you invertebrate experiments done at 11 K? That's -262.15 degrees Celsius!!

https://xolotl.readthedocs.io/en/master/reference/units/

**Comment by alec-hoyland** [comment]
You caught us. We use supercooled crabs.

Good catch, though. Submit a PR if it hasn't been fixed in master.
