### ISSUE TITLE
Initial voltage

### ISSUE THREAD

**Issue by luadam4c** [sg-s/xolotl#297]
I can't find in the documentation how you set the **initial voltage** for each compartment, i.e., the counterpart to `finitialize(v)` in NEURON

**Comment by alec-hoyland** [comment]
You just set it.

`x.comp.V = -65`

Xolotl integrates from the current state of the network. See `snapshot` and `closed_loop`.

**Comment by alec-hoyland** [comment]
I will add the appropriate documentation.

**Comment by alec-hoyland** [comment]
Currently the closed-loop text reads:

## Closed loop vs. open loop
The `closed_loop` flag (false or true) determines whether initial conditions should be reset before a new simulation. If `closed_loop` is true, successive simulations will use the current state of the `xolotl` object (e.g. the end state of the previous simulation if you run `integrate` twice in a row).

```matlab
% use current state of model as initial conditions
x.closed_loop = true
V = x.integrate;
```

You can set the initial conditions by setting the desired properties.

```matlab
% set the voltage to start at -50 mV in compartment 'comp'
x.comp.V = -50;
```

To quickly save the state of a network and return back to it later (such as for running multiple simulations)
you can use the [snapshot](snapshots.md) functionality.

**Comment by sg-s** [comment]
link doesn't work. i've added some text in the "construct model" section that should address this
