### ISSUE TITLE
Make approx_channels logical?

### ISSUE THREAD

**Issue by luadam4c** [sg-s/xolotl#299]
Right now it is a double 0/1, but wouldn't it make more sense to have it be logical?

**Comment by alec-hoyland** [comment]
No. Since that property needs to be read by the C++ code, it has to be an integer or double in cppland. MATLAB logicals don't work. See #255.

**Comment by luadam4c** [comment]
If there can be a `set.closed_loop()` that can interpret double as logical, can't there be a `set.approx_channels` that can interpret logical as double?

**Comment by sg-s** [comment]
BTW this is covered in the documentation [here](https://xolotl.readthedocs.io/en/master/reference/xolotl-properties/#closed_loop)

**Comment by luadam4c** [comment]
Yes I know it's in the documentation, that's why I raised the question. 

And yes I agree it has to be double for C++

But I anticipate that in the future, people will be reading parameters from Excel (with readtable() for instance), and then you would need to do the extra step of making some parameters double while others logical. If there is the possibility of allowing the user to place either double or logical for all these parameters, it would save a lot of trouble.

**Comment by sg-s** [comment]
OK, this is a bug, and it should match this behaviour

https://github.com/sg-s/xolotl/issues/255

**Comment by sg-s** [comment]
fixed.

**Comment by sg-s** [comment]
@luadam4c 

this is the behaviour now:

```
x.closed_loop = true; % OK
x.closed_loop = false; % OK
x.closed_loop = 0; % OK, interpreted as false
x.closed_loop = 1;  % OK, interpreted as true
x.closed_loop = 'true';  % error
x.closed_loop = 'F';  % OK, interpreted as true
```
