### ISSUE TITLE
x.plot() should have y-axis labelled "current" when in voltage clamp mode

### ISSUE THREAD

**Issue by luadam4c** [sg-s/xolotl#300]
When you run `x.plot()` in **voltage clamp** mode, there are inconsistencies:

1. The output is current for any compartment that is clamped, but is still voltage for any compartment that is not clamped. I think it makes sense to either show voltages for all compartments or show currents for all compartments.
2. For the output that is supposed to be **current**, the y-axis label still shows **voltage**.

**Comment by luadam4c** [comment]
1. Actually, I sort of like the fact that it shows voltage for the other compartments, then you could tell if other compartments without the electrode inserted is clamped or not.

**Comment by sg-s** [comment]
fixed
