### ISSUE TITLE
x.plot() should show command used

### ISSUE THREAD

**Issue by luadam4c** [sg-s/xolotl#301]
I think in general the default x.plot() should have a plot of the stimulus as well. That is, the command voltage for voltage clamp and the current protocal for current clamp. I suggest this trace be either the top-most subplot or the bottom-most subplot.

**Comment by sg-s** [comment]
too messy to implement; since in general there can be no "input" to the model, and if there is an input, there are as many inputs as compartments. 

remember that xolotl is trivially scriptable and expandable -- you can write a function that accepts a xolotl object that does this very easily:

```
function foo(x)

[V,I] = x.integrate;

% plot whatever you want

```
