### ISSUE TITLE
If a response is a horizontal line, it is invisible in x.plot()

### ISSUE THREAD

**Issue by luadam4c** [sg-s/xolotl#303]
See this plot I had from `x.plot()`:

![test_voltage_clamp1](https://user-images.githubusercontent.com/36715881/49982674-d2327980-ff2b-11e8-807d-b9d348dc5364.jpg)

Upon examination, the somatic current was actually 11 throughout starting from the 2nd data point.

However, it was not very evident what was going on at first. I suggest expanding the y-axis by 10% of total range by default.

**Comment by luadam4c** [comment]
If the default plot function is written in Matlab, this function might be useful
[compute_axis_limits.zip](https://github.com/sg-s/xolotl/files/2697811/compute_axis_limits.zip)

**Comment by sg-s** [comment]
thanks -- this will get fixed at some point.

**Comment by sg-s** [comment]
should be fixed now
