### ISSUE TITLE
Description of xolotl object should mention that it is a handle object

### ISSUE THREAD

**Issue by luadam4c** [sg-s/xolotl#309]
I didn't realize until recently that the xolotl object is actually a handle and cannot be copied by value with the syntax

```
x1 = x
```

Perhaps you can include this important fact right when you introduce the object here:
https://xolotl.readthedocs.io/en/master/how-to/construct-models/

I was modifying x1 and then didn't realize that x is now x1 ...

**Comment by sg-s** [comment]
yes, this should be somewhere...out of curiosity, what is the context in which you're copying xolotl objects?

**Comment by sg-s** [comment]
fixed
