### ISSUE TITLE
error when trying to manipulate models

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#334]
@luadam4c 

by default, a time-varying I_ext is overwritten with a static I_ext when a model is manipulated. if you want to preserve the time-varying I_ext (but lose the ability to manipulate I_ext), then use:

```
x.pref.use_I_ext = false;
```

**Comment by luadam4c** [comment]
> @luadam4c
> 
> by default, a time-varying I_ext is overwritten with a static I_ext when a model is manipulated. if you want to preserve the time-varying I_ext (but lose the ability to manipulate I_ext), then use:
> 
> ```
> x.pref.use_I_ext = false;
> ```

Thanks! It works!

This is the error that would sometimes show up when I move the slider too quickly. But it's not a big deal:

> Error using xolotl/set.I_ext (line 231)
> Size of I_ext is incorrect::1st dimension size should be 10000
> 
> Error in cpplab/subsasgn (line 68)
> self = builtin('subsasgn',self,S,value);

**Comment by sg-s** [comment]
are you setting I_ext while you're manipulating it? 

with this setting

```
x.pref.use_I_ext = false;
```

I_ext shouldn't be touched at all...

**Comment by luadam4c** [comment]
> are you setting I_ext while you're manipulating it?
> 
> with this setting
> 
> ```
> x.pref.use_I_ext = false;
> ```
> I_ext shouldn't be touched at all...

I thought you just said that if I use this setting then I can change I_ext
Again, I'm not trying to manipulate I_ext as a parameter, but rather update it while I manipulate other parameters such as Leak.gbar

**Comment by sg-s** [comment]
sure, you can change it, but the error you're getting makes sense now:

```
Size of I_ext is incorrect::1st dimension size should be 10000
```

you have to size I_ext correctly

**Comment by luadam4c** [comment]
> maybe you're changing t_end or sim_dt when you're manipulating the model?

Yes I am changing t_end. The voltage clamp simulation is shorter. I'm switching back and forth between voltage clamp and current clamp. However, I do reset t_end before changing I_ext. This error doesn't always occur, only when I move the slidebar too quickly

**Comment by sg-s** [comment]
ah -- so if you're changing t_end, then your I_ext will be constantly mismatched. that's why you see the error

**Comment by luadam4c** [comment]
> ah -- so if you're changing t_end, then your I_ext will be constantly mismatched. that's why you see the error

How come I don't see the error every time I change t_end though?

**Comment by sg-s** [comment]
the error is thrown only when the length of I_ext is not equal to x.t_end/x.sim_dt

**Comment by luadam4c** [comment]
> the error is thrown only when the length of I_ext is not equal to x.t_end/x.sim_dt

I didn't do anything to my code but whatever update you did recently seems to have eliminated this error! Thanks!
