### ISSUE TITLE
consider leaving readthedocs and switching to hosting on github pages

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#337]
because we can't get custom 404 pages on readthedocs.

see 

https://github.com/rtfd/readthedocs.org/issues/5050

**Comment by alec-hoyland** [comment]
Well that's a pain. I don't know what we can do about it except to switch. Fortunately, the docs are written in Markdown, so displaying on GitHub shouldn't be a problem. Is this going to ruin our pretty theme though?

**Comment by alec-hoyland** [comment]
I guess the other question is how much of a pain is not having custom 404 pages?

**Comment by sg-s** [comment]
no, it should be exactly the same. docs are built into `site/` and github-pages simple uses that

**Comment by alec-hoyland** [comment]
Oh, brilliant.
