### ISSUE TITLE
best practice/feature proposal: arbitrary stimulation of synapses

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#348]
I've got an interesting project I'm working on where I need to stimulate a post-synaptic neuron by activating a synapse. 
* Is there a way to provide a spike train to a synapse to cause it to spike and stimulate a post-synaptic cell (without a presynaptic compartment)?
* If not, is the best practice to voltage-clamp the pre-synaptic (dummy) compartment with some custom waveform and have its only function be to provide a synapse onto the post-synaptic compartment of interest?
* If not, is the best practice to come up with dynamics which result in the custom waveform and then implement those dynamics in the pre-synaptic compartment?

**Comment by sg-s** [comment]
> * Is there a way to provide a spike train to a synapse to cause it to spike and stimulate a post-synaptic cell (without a presynaptic compartment)?

no

> * If not, is the best practice to voltage-clamp the pre-synaptic (dummy) compartment with some custom waveform and have its only function be to provide a synapse onto the post-synaptic compartment of interest?

I actually did this for [this paper](https://www.physiology.org/doi/abs/10.1152/jn.00820.2017) and what i did was to create an empty compartment with zero channels and voltage clamp it. the only thing this compartment has is that it is presynaptic to the synapse in question, so it effectively acts as a handle to the synapse

**Comment by sg-s** [comment]
what's the objection to creating an empty compartment and voltage clamping that? not sure providing a spike train would be less cumbersome, since we'll have to figure out how to feed this into the model. right now, the "spike train" = voltage clamp of some dummy compartments

**Comment by alec-hoyland** [comment]
Yeah, I think voltage clamping an empty compartment is the best practices e for this use case.

If you need a spike train or some reason, you can either (a) set up the voltage clamped compartment to have actual full action potentials, or (b) use a mechanism or tweaked synapse to turn a binary voltage clamped "trace" into the voltage the synapse needs to produce the desired response.

**Comment by sg-s** [comment]
i don't think you need to mimic action potentials -- just clamp the voltage to a binary voltage series (-60 always, except when it spikes, then it's +50)

you might want to specify a spike "width"

**Comment by alec-hoyland** [comment]
That is what I am thinking as well. I'm pretty sure this is what NEURON does when you ask it to stimulate a synapse at time _t_.
