### ISSUE TITLE
Use inline functions to reduce overhead

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#349]
http://www.cplusplus.com/articles/2LywvCM9/
Inline functions might speed up our C++ code, especially for things like this

```c++
double NMDAergic::sdot(double V_pre, double V_post, double s_)
{
    double ss = ss_core(V_pre);
    return (s_inf(ss) - s_) / tau_s(ss) * 1.0 / (1.0 + Mg / 3.57 * exp(-0.062*V_post));
}
```
where `s_inf()` and `tau_s()` are small functions that are called at each time-point. What I *don't know* is how much the C++ compiler is already inlining.

**Comment by sg-s** [comment]
it makes no measurable difference. I tried inlining all functions in all conductances, and measured speeds with and without.
