### ISSUE TITLE
Could not find md5hash, can't create xolotl object

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#352]
An important dependency for xolotl is currently undergoing reorganization. This has resulted in a solvable error when attempting to run

```matlab
x = xolotl
```

The error looks like this:

```matlab
Error using cpplab (line 57)
Could not find mtools.crypto.md5hash on the path.

Error in xolotl (line 127)
	function self = xolotl()

Error in test (line 8)
x = xolotl;
 ```

This error occurs if
* `cpplab` is up-to-date, and
* the core folder for `srinivas.gs_mtools` is not added to your matlab path

It *does not* occur if you are using the toolbox releases.

You can fix this error by pulling from `mtools` and `cpplab` and then adding `../srinivas.gs_mtools/` to your matlab path. While it is also possible to solve this problem by rolling back `cpplab`, this is not recommended.

**Comment by sg-s** [comment]
should be fixed now
