### ISSUE TITLE
this is how MATLAB automatically links other help files together

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#360]
If you have the words "See Also" in a comment, followed by the name of some function or method, MATLAB builds a link for it that is displayed in `help foo`

This should be used, and python scripts should be changed so that we can cross-link help files in both MATLAB and the docs

**Comment by alec-hoyland** [comment]
### Problem
Currently this is what the "See Also" section of our documentation looks like

```md
!!! info "See Also"
    * [xolotl.update](#update)
```
And, in MATLAB:

```
!!! info "See Also"
    * [xolotl.update](#update)
```

MATLAB doesn't like if you try to get clever with it. That is,
```md
!!! info "See Also" xolotl.update
```
does not do what we want. Specifically, the fact that there are characters before the `See Also` causes the problem.

### Proposed Solution
Add a unique identifier (that is _not_ valid  C++ or MATLAB code), such as `# @@@` to serve as identifiable tags in each method definition. Then the Python script can delimit what should be included as valid Markdown and what should not be. Then, anything after the closing `#@@@` tag can be additional MATLAB documentation that is not included in the Markdown that is added to the methods page.

The code would look something like this

```matlab
% @@@
% ### uninstall
%
% **Syntax**
%
% ```matlab
% xolotl.uninstall
% x.uninstall
% ```
%
% **Description**
% ... ... ...
%
% !!! info "See Also"
%     ->xolotl.update
% @@@
% See Also xolotl.update
```

In MATLAB, `help xolotl.update` would yield something like

```
  @@@
  
  ... ... ...

  !!! info "See Also"
      ->xolotl.update
 
  @@@
  See Also xolotl.update
```

**Comment by sg-s** [comment]
there is a simpler solution: use the MATLAB syntax (which is the exact words "See Also")

and then modify the python script to translate that into valid markdown

**Comment by alec-hoyland** [comment]
I'm so glad you volunteered to write the python :)
