### ISSUE TITLE
Consider using natural sorting for slice-compartment names

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#362]
Consider using [natsort](https://www.mathworks.com/matlabcentral/fileexchange/47434-natural-order-filename-sort) to name compartments during slicing (and sorting during `find`) so that compartments can be named

`compname9`
`compname10`

instead of 

`compname09`
`compname10`

This is a somewhat trivial choice, but it might reflect an underlying design philosophy.

---

Here is a situation in which it might matter:

```matlab
% instantiate the apical dendrite compartments
x.add('compartment', 'ApicalDendrite', 'Cm', 30, 'radius', 2.89/1e3, 'len', 10*120/1e3);
...
x.ApicalDendrite.add('Leak', 'gbar', 1, 'E', -50);

% instantiate the basal dendrite compartments
x.add('compartment', 'BasalDendrite', 'Cm', 30, 'radius', 4.23/1e3, 'len', 8*125/1e3);
...
x.BasalDendrite.add('Leak', 'gbar', 1, 'E', -50);

% instantiate the somatic compartment
x.add('compartment', 'Somatic', 'Cm', 30, 'radius', 2.42/1e3, 'len', 110/1e3);
...
x.Somatic.add('Leak', 'gbar', 1, 'E', -50);

% slice the dendrites
x.slice('ApicalDendrite', 10);
x.slice('BasalDendrite', 8);
x.Somatic.tree_idx = 0;

% connect the apical and the basal dendrites to the soma
x.connect('ApicalDendrite10', 'Somatic', 'Axial', 'gmax', 100);
x.connect('Somatic', 'ApicalDendrite10', 'Axial', 'gmax', 100);
x.connect('BasalDendrite1', 'Somatic', 'Axial', 'gmax', 100);
x.connect('Somatic', 'BasalDendrite1', 'Axial', 'gmax', 100);
```

since there are 8 basal compartments and 10 apical compartments, they are named based on how many there are of each type, not with respect to any other slicing. `ApicalDendrite` here goes from 01 to 10 and `BasalDendrite` goes from 1 to 8.

**Comment by sg-s** [comment]
the problem is that lots of things traverse the object tree in alphabetical order -- including some C++ code. to include this natural sorting here, we will have to change how the tree is parsed everywhere -- in C++ and in cpplab

**Comment by alec-hoyland** [comment]
Yeah, that's fair. Do you think it is something worth devoting time to change? I am not so sure.

**Comment by sg-s** [comment]
at some point, perhaps. for multi-compartment models i think the higher priority is figuring out why models don't behave as we expect them to (like [this one](https://github.com/sg-s/xolotl/issues/324))

**Comment by alec-hoyland** [comment]
So here's actually a great example of where it gets weird: in `xolotl.examples.BurstingCable('N', 2)`. 
This is because the last step in the function is to connect the `CellBody` compartment with the `Neurite01` compartment. The latter is named `Neurite1` if there are less than 10 neuritic compartments.

**Comment by sg-s** [comment]
yes, that's a problem

**Comment by sg-s** [comment]
this won't happen since i don't see an easy way of doing this
