### ISSUE TITLE
can xolotl be multi-threaded?

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#364]
some reading:

* [mex multithreading](https://www.mathworks.com/matlabcentral/fileexchange/21233-mex-multithreading)
* [max_in_place](https://www.mathworks.com/matlabcentral/fileexchange/68237-max_in_place-example-of-multi-threaded-mex-function)
* [yair](https://undocumentedmatlab.com/blog/multi-threaded-mex)
* [threads in C++](https://hackernoon.com/learn-c-multi-threading-in-5-minutes-8b881c92941f)

**Comment by sg-s** [comment]
## one way of doing this:

parallelize integration of conductances and mechanisms in `compartment.hpp` by creating threads every time step, and destroying them every time step. this is clearly sub-optimal, but it may offer a speed up

to do this, 

- [ ] verify that xolotl compiles with `thread`
- [ ] figure out how to create a vector of threads
- [ ] figure out how to pass methods of objects referred to by pointers to `thread`
- [ ] check if there is any speedup

**Comment by sg-s** [comment]
vector of threads

https://www.justsoftwaresolutions.co.uk/threading/managing_threads_with_a_vector.html

**Comment by sg-s** [comment]
creating a new thread every time step is extremely slow. what we want is a [thread pool](https://github.com/mtrebi/thread-pool) that we can offload work onto

**Comment by sg-s** [comment]
it looks like creating and destroying threads every time step is extremely stupid and slow. instead:

- [ ] create threads when initialized (a hook into `addConductance` so there is on thread for each conductance?)
- [ ] write an infinitely integrating method of conductance
- [ ] this infinitely integrating method is what runs on the thread
- [ ] but, it only runs if it needs to -- some sort of synchronisation with the compartment needed
- [ ] when done, it should terminate
- [ ] and join() should be called for safety

**Comment by sg-s** [comment]
but first, a problem is that `conductance` cannot read things from `compartment`

**Comment by sg-s** [comment]
now need to implement some sort of synchronization b/w the threads

see:

* https://freecontent.manning.com/synchronizing-concurrent-operations-in-c/

**Comment by sg-s** [comment]
the speedups can be real, and significant: 

on a model with 5 channels, we can go from 90X (single threaded) to over 200X (using five threads)

**Comment by alec-hoyland** [comment]
Wow

**Comment by sg-s** [comment]
not even close -- it runs using multiple threads now but the integration is rubbish since all the things happen all the time and there is no guarantees of what happens when. 

hopefully i'll be able to synchronize threads, and that should a) make it much faster and b) make it correct

**Comment by sg-s** [comment]
this is very hard to implement -- need to figure out the right combination of mutexes and conditon variables to use. also, the improvement in `approx_channel` performance means that code is now 3X faster.

**Comment by alec-hoyland** [comment]
> but first, a problem is that `conductance` cannot read things from `compartment`

At the least, this should be fixed now.

**Comment by sg-s** [comment]
Hmm, thanks for reminding me. I need to learn how to synchronise threads in C++

**Comment by sg-s** [comment]
Not worth it, except as a programming exercise and learning how to use threads in C++
