### ISSUE TITLE
Headers for methods aren't displaying correctly on documentation

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#366]
See here: https://xolotl.readthedocs.io/en/master/reference/matlab/xolotl/

![Screenshot_20190312_135519](https://user-images.githubusercontent.com/30243182/54223743-882b4680-44ce-11e9-8ccc-a855193b35b9.png)

**Comment by sg-s** [comment]
that's because there's a leading space...

need to fix the python script to strip spaces

**Comment by sg-s** [comment]
fixed
