### ISSUE TITLE
update downloads toolbox but doesn't erase .mltbx file after install

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#378]
The `xolotl.update` command works great, but it leaves the `xolotl.mltbox` file laying around in the current working directory.

## Proposed Fix
Add to `xolotl.update`:

```matlab
delete(fullfile(pwd, 'xolotl.mltbx'))
```

**Comment by sg-s** [comment]
update will have to be overhauled -- it needs to work better for git, and i think it also doesn't delete old toolbox directories on windows.

**Comment by sg-s** [comment]
This should be fixed. 

@alec-hoyland reopen if not
