### ISSUE TITLE
Variance of subunit noise

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#388]
What is the variance of the subunit noise for SDE simulation? Wikipedia seems to think it should be the time step.

**Comment by alec-hoyland** [comment]
It looks like `gaussrand` gives a normal distribution with mean 0 and standard deviation 1.

**Comment by sg-s** [comment]
![Screen Shot 2019-04-01 at 10 19 25 AM](https://user-images.githubusercontent.com/6005346/55334666-ac43cd00-5467-11e9-8d30-2aae4c017b42.png)
