### ISSUE TITLE
Dynamic variables of synapses show up in manipulate 

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#390]
## Operating System 

Manjaro Arch

## Output of "version" command in MATLAB

    '9.5.0.1033004 (R2018b) Update 2'

## Output of "mex.getCompilerConfigurations('C++')" in MATLAB

```matlab
>> mex.getCompilerConfigurations('C++')

ans = 

  CompilerConfiguration with properties:

             Name: 'g++'
     Manufacturer: 'GNU'
         Language: 'C++'
          Version: ''
         Location: '/usr/bin/g++'
        ShortName: 'g++'
         Priority: 'A'
          Details: [1×1 mex.CompilerConfigurationDetails]
       LinkerName: '/usr/bin/g++'
    LinkerVersion: ''
           MexOpt: '/home/alec/MATLAB/R2018b/bin/glnxa64/mexopts/g++_glnxa64.xml'
```
# Bug 1

Synapse gating variables still show up in manipulate.

## What I did

```matlab
demo_stg
x.manipulate()
```

## What I expected

I expected for `'synapses*.s'` to not appear, as specified in line 79 of `manipulate`.

## What happened

![image](https://user-images.githubusercontent.com/30243182/55501163-d0dea700-5617-11e9-9008-1dd2f85a1cdd.png)

# Bug 2

## What I did

```matlab
demo_stg
x.manipulate({'*gbar', '*gmax'})
```

## What I expected

Manipulate figure with only `gmax` and `gbar` properties of all conductances and synapses with sliders.

## What happened

```
Error using xolotl/manipulate (line 141)
This parameter could not be resolved: *gbar
```

**Comment by alec-hoyland** [comment]
The first bug is caused by the `find` function on line 79 failing to find `synapses*s` since it doesn't know what `synapses` is. The second bug is caused by the try/catch block later on, since `value` expects a scalar (and `x.get('*gbar')` is rarely a scalar).

**Comment by sg-s** [comment]
This

```
x.manipulate({'*gbar', '*gmax'})
```

works as expected. Wildcard matching only works with one wildcard, to do what you want, use:

```
x.manipulate([x.find('*gbar'); x.find('*gmax')])
``

**Comment by sg-s** [comment]
and yes, synaptic gating variables do show up. However, the cost of them showing up is small (you can safely change them, and they don't do anything). Fixing this will introduce needless complexity. wontfix.
