### ISSUE TITLE
NMDA synapses should have 3 "state variables"

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#415]
They should be
* the synaptic gating variable (integrated)
* the magnesium block gating variable (instantaneous)
* the current

Currently there are only two; the two gating variables are wrapped up in each other as a product. This is less helpful for analysis, since they have different timescales.

**Comment by sg-s** [comment]
If something is "instantaneous", then it has no dynamics -- typically, a state variable is something that has a ODE

**Comment by alec-hoyland** [comment]
Yes, and we should talk about this.
The equation for the NMDA synapse is:

```
I = gmax * s * u * (V - E)
```

Where `s` has to be integrated and `u` is a pure function of the postsynaptic potential `V`. Problem is, I really want separate readouts of `s` and `u` because `s = s(Vpre, t)` and `u = u(Vpost)`, and it's a pain to reason about them combined.

**Comment by alec-hoyland** [comment]
I can get the "pure" `s` time-series by multiplying by `u` (the way that things are now, `u` is wrapped into `s`), but then I have to compute `u` manually. Should `u` be read out during integration as another state variable (even though it's not a state variable), or should it be wrapped into `s`, or should it be computed separately but not read out at all (keeping `s` as "pure" `s`)?

**Comment by alec-hoyland** [comment]
Another thing to consider. I've been fucking up by incorporating `u` into `s`. 
Writing `s = s * u` at any point ruins `s` by causing its value to jump. So whatever the fix is, it needs to respect this. Currently it's broken, but fixed in a new branch.
