### ISSUE TITLE
Cloning using git leads to detached heads in submodules

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#428]
Apparently this is a rookie error, and the fix is here:

https://stackoverflow.com/questions/18770545/why-is-my-git-submodule-head-detached-from-master

**Comment by sg-s** [comment]
Problem persists in latest commit (Jul7 17)

```
git clone --recursive git@github.com:sg-s/xolotl.git
cd /code/xolotl/@xfit
git status
HEAD detached at 7c79ca5
nothing to commit, working tree clean
```

**Comment by alec-hoyland** [comment]
Hmm. I can reproduce this. 
This seems to be the answer:

```bash
git clone --recursive git@github.com:sg-s/xolotl.git
cd xolotl
git submodule update 
git submodule foreach git checkout master 
git submodule foreach git pull origin master 
```

**Comment by sg-s** [comment]
That's a workaround, but this means something is misconfigured

**Comment by alec-hoyland** [comment]
Alternatively

```bash
git submodule add -b <branch> <repository> [<submodule-path>]
```

**Comment by sg-s** [comment]
Yeah, that's the workaround in the link I posted at the top. If we were doing things correctly, `git clone --recursive` would just work

**Comment by alec-hoyland** [comment]
So

```bash
git submodule add -b master --name xfit git@github.com:foo/bar.git @xfit
```

Is this what we need?

**Comment by alec-hoyland** [comment]
Let me try this, and I'll get back to you.

**Comment by alec-hoyland** [comment]
No luck.

I ended up with a `.gitmodules` file that reads:

```gitconfig
[submodule "xfit"]
        path = @xfit
        url = git@github.com:sg-s/xfit.git
        branch = master
```

But when I clone, switch to branch `submodule-b`, and `git submodule update --init`, I am stuck in a branchless state.

**Comment by sg-s** [comment]
maybe this helps? 

https://gist.github.com/slavafomin/08670ec0c0e75b500edbaa5d43a5c93c

**Comment by alec-hoyland** [comment]
They also use a workaround there. They just clone the repository recursively, and then force the submodules to track the correct branches. I will test this out.

**Comment by sg-s** [comment]
Maybe this is expected behaviour? I tried cloning this example by Github, and it behaves the same way:

https://github.com/githubtraining/example-dependency

**Comment by alec-hoyland** [comment]
I think it is. Either the `git submodule foreach` commands or the gist you just posted work. I like the gist more. I will write something up.

**Comment by sg-s** [comment]
So right now, if you run

```
git clone --recursive git@github.com:sg-s/xolotl.git
```

it ....works. You get all the code, and MATLAB can see the xfit code. The only problem is that xfit has a detached head, which shouldn't matter unless you are making changes to xfit

**Comment by sg-s** [comment]
And a simple `git checkout master` fixes that

**Comment by alec-hoyland** [comment]
Yep.

This is just a more adaptable way of doing it:

```bash
git submodule foreach -q --recursive 'git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch || echo master)'
```

Since it asks what's configured in the `.gitmodules` config file.
