### ISSUE TITLE
Implement a differential evolution algorithm

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#434]
A differential evolution algorithm might be even better than particle swarm. It's worth testing at some point.
[Vesterstrom & Thomas 2004](https://pdfs.semanticscholar.org/3a69/6bc9fbcbd6c021d9cedd415ad71bba964262.pdf)
[Zhang & Wei 204](https://ieeexplore.ieee.org/abstract/document/6885702/)
[Iwan *et al.* 2014](https://www.sciencedirect.com/science/article/pii/S1877705812027178)

**Comment by sg-s** [comment]
Won't happen, because xfit is really a wrapper around whatever MATLAB in its wisdom provides to us in the Global Optim Toolbox
