### ISSUE TITLE
how do we introduce relations between parameters?

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#436]
so that we can constrain solutions to be those where `NaV.gbar` is always > `HCurrent.gbar` , for example

**Comment by alec-hoyland** [comment]
My initial thought is to add a list of checks to go through each time someone tries to change a parameter.

For example, say I want to add the rule, "`NaV.gbar` > `HCurrent.gbar`":
Then anytime I `set` or object-notation-set a property, run through all the rules to make sure all are followed before proceeding.

I'm not sure what the best way to make the list of rules is though.

**Comment by sg-s** [comment]
This is possible using MATLAB's built in tools for example, see: https://www.mathworks.com/help/optim/ug/linear-constraints.html
