### ISSUE TITLE
Write documentation explaining how to use xolotl in parallel processing tasks

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#439]
Something is very wrong somewhere

**Comment by sg-s** [comment]
Ideally, we don't want xgrid -- we want to use native MATLAB tools like parfor to write bare code that just works. Why shouldn't this work?

**Comment by sg-s** [comment]
It's actually possible to do this:

```
all_gbar = linspace(0,2e3,10);

V = zeros(10e4,10);

parfor i = 1:10
	x.set('AB.NaV.gbar',all_gbar(i));
	V(:,i) = x.integrate;
end


```

**Comment by alec-hoyland** [comment]
That might have problems for two reasons.

1. `parfor` might have problems with sharing the object -- it would need to spawn multiple copies of the object (this is probably fine, but would need to be coded if MATLAB can't do it automatically).

2. I am doubtful of MATLAB's ability to parallelize over multiple clusters. The xgrid daemon feature-set seems good to me.

However, I think in general you are correct: given a matrix of parameters and an xolotl object, it *should* be possible to write something along the lines of:

* Spawn `n` workers
* For each worker, clone the object
* ...
blah blah blah

**Comment by alec-hoyland** [comment]
Trying now...

**Comment by sg-s** [comment]
Well, this code is way more elegant -- you don't need xgrid at all! xgrid still useful for multiple computers, but now we're using MATLAB's native multi-processing

**Comment by sg-s** [comment]
The catch is you can't assign variables using properties, you need to use `set` and `get`:

```

% this won't work
parfor i = 1:10
	x.AB.NaV.gbar = all_gbar(i);
	V(:,i) = x.integrate;
end

% this works
parfor i = 1:10
	x.set('AB.NaV.gbar',all_gbar(i));
	V(:,i) = x.integrate;
end



```

**Comment by alec-hoyland** [comment]
Aha! That explains why I've had trouble in the past.
Actually, this makes it super easy, and is another reason that set and get are the best.

I will code up what we need and update the documentation.

**Comment by sg-s** [comment]
No, no, hang on...some things are still mysterious to me

**Comment by sg-s** [comment]
OK, I have managed to convert the example script that uses `xgrid` to idiomatic MATLAB using `parfor`. It runs much faster, and obviously doesn't need `xgrid` at all, which is a **HUGE** win

**Comment by sg-s** [comment]
OK, I wrote [a demo that runs a parameter scan in parallel](https://github.com/sg-s/xolotl/blob/master/examples/demo_parallel.m) using `parfor`, and I'm getting speeds in excess of 700X

**Comment by sg-s** [comment]
OK, after further testing, everything seems to work. 

Some things I have learnt: 

1. You cannot directly set parameters using dot notation in `parfor` loops. Use the `set` method instead (Maybe last time we tried this, we didn't have the `set` method yet?)
2. You can however read out things using dot notation
3. It's way faster than xgrid, presumably because there are smaller communication overheads b/w workers

**Comment by alec-hoyland** [comment]
xgrid also relies on saving and loading .mat files, which is a huge overhead. The parfor method is great for local simulations (and will work on a big computing cluster too...just not on two clusters simultaneously).

**Comment by sg-s** [comment]
Exactly. And I feel like the speedup we get now will offset the use of a single computer. So xgrid is mostly deprecated at the moment

**Comment by sg-s** [comment]
I'm going to write a "how-to" about this

**Comment by alec-hoyland** [comment]
If you want to. I just started on one...rewriting "run-simulations-in-parallel", but if you want to, by all means.

**Comment by sg-s** [comment]
OK, never mind, go for it.
