### ISSUE TITLE
Proposal: replace the 'vol' property with a 'depth' property

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#447]
A lot of calcium mechanisms (importantly, [this one](https://www.sciencedirect.com/science/article/pii/S0006349593811901)) use a depth parameter instead of a volume parameter. It would save 1 flop per iteration to use a depth parameter instead of a volume.

Compare: 

```C++
-(phi*(comp->i_Ca)*(comp->A)/(192971*(comp->vol)))
```

with

```C++
-(phi*(comp->i_Ca)/(192971*(comp->depth)))
```

The volume would then be computed as `x.AB.A * x.AB.depth` for compartment `AB`.

Is volume super useful elsewhere? I'm very disinterested about whether making this (breaking) change would make a lot of positive good.

**Comment by sg-s** [comment]
No, will not happen

- for backwards compataibility
- "depth" unclear in most context, volume makes sense

If you want to save operations, you can pre-compute that value and store it at initialization and then use that. For an example of optimizations like this, look [here](https://github.com/sg-s/xolotl/blob/6dbfaf1da92c0c3c02d96910403efe59ea3d8387/c%2B%2B/mechanisms/prinz/CalciumMech.hpp#L77)

**Comment by alec-hoyland** [comment]
That all makes sense to me.
