### ISSUE TITLE
rheobase is broken

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#462]
The function does not work the way that it should. Or at least, it gives results that may be misleading.

For example, the Hodgkin-Huxley model (`xolotl.examples.HodgkinHuxley`) begins tonically spiking at around 0.0055 nA of injected current, and undergoes depolarization block at higher injected currents (see 0.007 nA, for example).

The optimization algorithm with default options fails because the model blows up -- too much injected current causes the membrane potential to go to infinity.

```matlab
>> x.rheobase
Error using xtools.findNSpikes (line 39)
V cannot contain NaNs

Error in xolotl/rheobase/nSpikesForCurrent (line 77)
	N = xtools.findNSpikes(V(:,1)) - 1;

Error in xolotl/rheobase>@(y)nSpikesForCurrent(self,y) (line 64)
I = fminbnd(@(y) nSpikesForCurrent(self,y) ,options.I_min,options.I_max);

Error in fminbnd (line 228)
x= xf; fx = funfcn(x,varargin{:});

Error in xolotl/rheobase (line 64)
I = fminbnd(@(y) nSpikesForCurrent(self,y) ,options.I_min,options.I_max);
```

**Comment by alec-hoyland** [comment]
I have not had success with the `BurstingNeuron('prefix', 'liu')` model, nor this one:

```matlab
x = xolotl('temperature', 36, 'temperature_ref', 22);
x.add('compartment', 'comp', 'Cm', 10, 'A', 1e-3, 'vol', 1e-6, 'Ca_out', 2e3);
x.comp.add('buchholtz/CalciumMech', 'Ca_in', 0.2, 'tau_Ca', 250, 'phi', 1);
x.comp.add('soplata/CaN', 'gbar', 0.25);
x.comp.add('destexhe/CaT', 'gbar', 1);
x.comp.add('soplata/Kd', 'gbar', 200);
x.comp.add('soplata/NaV', 'gbar', 2000);
x.comp.add('Leak', 'gbar', 0.1);
```

**Comment by sg-s** [comment]
No, this is fine. (insert gif here)

for the HH model, injecting too much current will cause it to blow up. (which makes sense)

specifying a `I_max` solves the issue:

```
x.rheobase('I_max',1e-3)
```

**Comment by alec-hoyland** [comment]
I don't suppose there's a way to tell the optimizer to only go upwards?

**Comment by sg-s** [comment]
just specify bounds, you should be fine.

See:

```
x.fI('I_max',1e-3,'I_min',0,'n_steps',20)
```

identfies the rheobase correctly:

<img width="812" alt="Screen Shot 2019-08-13 at 17 35 23" src="https://user-images.githubusercontent.com/6005346/62979063-d089c000-bdf0-11e9-98fe-260c95ad9010.png">

**Comment by alec-hoyland** [comment]
Looks good to me.
