### ISSUE TITLE
Forcing exponential Euler integration on conductances makes it generally impossible to use conductances that are nonlinear in voltage

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#464]
We need a general purpose solver that works when the conductances simply specify the current, and that is what we use to solve the model. This can be more unstable, but it needs to be there

**Comment by alec-hoyland** [comment]
This is a great idea. It means we can do equation-oriented models as well.

**Comment by sg-s** [comment]
Possible way forward is to check if ALL conductances do not implement their own getCurrent methods. If they don't, then we can safely assume that they are all linear and use the normal methods we have. If **any** one of them defines their own getCurrent method, then fall back to explicitly computing the current for each conductance, and using the currents to integrate the voltage in that compartment.

**Comment by sg-s** [comment]
Unfortunately it looks like we can't do that:

https://stackoverflow.com/questions/4741271/ways-to-detect-whether-a-c-virtual-function-has-been-redefined-in-a-derived-cl

**Comment by sg-s** [comment]
Or, set a global (xolotl-level) flag specifying how the compartment should be integrated. Is `use_current = 1`, then when conductances are integrated, the currents are also computed and accumulated, and the total current is used to update the voltage.
