### ISSUE TITLE
Documentation should discourage users from creating identical models with different component names

### ISSUE THREAD

**Issue by luadam4c** [sg-s/xolotl#468]
Try this code:

```
xolotl.update

y = xolotl('temperature', 36, 'temperature_ref', 22);

y.add('compartment', 'soma', 'Cm', 10, 'A', 1e-3, 'vol', 1e-6, 'Ca_out', 2e3);

y.soma.add('buchholtz/CalciumMech', 'Ca_in', 0.2, 'tau_Ca', 250, 'phi', 1);

y.soma.add('soplata/CaN', 'gbar', 0.25);
y.soma.add('destexhe/CaT', 'gbar', 1);
y.soma.add('soplata/Kd', 'gbar', 200);
y.soma.add('soplata/NaV', 'gbar', 2000);
y.soma.add('Leak', 'gbar', 0.1);

y.I_ext = 0.07;

y.plot;

close all
clear y

x = xolotl('temperature', 36, 'temperature_ref', 22);

x.add('compartment', 'comp', 'Cm', 10, 'A', 1e-3, 'vol', 1e-6, 'Ca_out', 2e3);

x.comp.add('buchholtz/CalciumMech', 'Ca_in', 0.2, 'tau_Ca', 250, 'phi', 1);

x.comp.add('soplata/CaN', 'gbar', 0.25);
x.comp.add('destexhe/CaT', 'gbar', 1);
x.comp.add('soplata/Kd', 'gbar', 200);
x.comp.add('soplata/NaV', 'gbar', 2000);
x.comp.add('Leak', 'gbar', 0.1);

x.I_ext = 0.07;

x.plot;
```

This is my output:

> Installed version:
> 19.8.14
> Warning: You are using gcc version '7.4.0'. The version of gcc is not supported. The version
> currently supported with MEX is '6.3.x'. For a list of currently supported compilers see:
> https://www.mathworks.com/support/compilers/current_release. 
> > In xolotl/compile (line 55)
>   In xolotl/integrate (line 109)
>   In xolotl/plot (line 128) 
> Error using matlab.graphics.axis.Axes/set
> Value must be a 1x2 vector of numeric type in which the second element is larger than the first
> and may be Inf
> 
> Error in xolotl/plot (line 169)
> 			set(self.handles.ax(i),'YLim',[0 max_Ca])

Now if I reorder the two models:

```
xolotl.update;

x = xolotl('temperature', 36, 'temperature_ref', 22);

x.add('compartment', 'comp', 'Cm', 10, 'A', 1e-3, 'vol', 1e-6, 'Ca_out', 2e3);

x.comp.add('buchholtz/CalciumMech', 'Ca_in', 0.2, 'tau_Ca', 250, 'phi', 1);

x.comp.add('soplata/CaN', 'gbar', 0.25);
x.comp.add('destexhe/CaT', 'gbar', 1);
x.comp.add('soplata/Kd', 'gbar', 200);
x.comp.add('soplata/NaV', 'gbar', 2000);
x.comp.add('Leak', 'gbar', 0.1);

x.I_ext = 0.07;

x.plot;

close all
clear x

y = xolotl('temperature', 36, 'temperature_ref', 22);

y.add('compartment', 'soma', 'Cm', 10, 'A', 1e-3, 'vol', 1e-6, 'Ca_out', 2e3);

y.soma.add('buchholtz/CalciumMech', 'Ca_in', 0.2, 'tau_Ca', 250, 'phi', 1);

y.soma.add('soplata/CaN', 'gbar', 0.25);
y.soma.add('destexhe/CaT', 'gbar', 1);
y.soma.add('soplata/Kd', 'gbar', 200);
y.soma.add('soplata/NaV', 'gbar', 2000);
y.soma.add('Leak', 'gbar', 0.1);

y.I_ext = 0.07;

y.plot;
```

I get a different error:

> Installed version:
> 19.8.14
> Warning: You are using gcc version '7.4.0'. The version of gcc is not supported. The version
> currently supported with MEX is '6.3.x'. For a list of currently supported compilers see:
> https://www.mathworks.com/support/compilers/current_release. 
> > In xolotl/compile (line 55)
>   In xolotl/integrate (line 109)
>   In xolotl/plot (line 128) 
> Error using X_f3ebe2c1cb0fd6a62cb59b39410da4f0
> gbars cannot be negative for any conductance
> 
> 
> Error in xolotl/integrate (line 175)
> [results{1:n_outputs+1}] = f(arguments,self.I_ext',self.V_clamp');
> 
> Error in xolotl/plot (line 128)
> [V, Ca, ~, currents] = self.integrate;

What's going on?

Also, I know you probably don't mean it, but when you close an issue before I feel that the issue is resolved, I feel like you are just brushing off my concerns. I thought you intended to promote xolotl for widespread use. If so, wouldn't you want to make sure everything is working on my end as well? It takes time to already to learn a new program. It takes even more time to report potential bugs and test things out. To be honest, even though xolotl has a lot of great features, it still has a lot to improve on to meet everything that more established simulators like NEURON provides. It takes time to learn how to write mechanisms with NMODL, but I don't think writing C++ files are any easier. Therefore if this program is to be promoted for public use, a lot more needs to be done in terms of documentation and testing.

**Comment by sg-s** [comment]
Yes...

This is expected behaviour. What you're doing is constructing two identical models, but where the compartment is named differently. Because the two models are identical, xolotl uses the same binary to integrate them. However, names don't resolve correctly because the names of compartments are different. Therefore, you will get unpredictable results and rather cryptic errors.

Perhaps a more productive approach would be try to figure out why you are doing this? If you have the exact same model twice, then there is no need to represent it with two different objects -- they are the same. 

If you *do* want to represent it with two objects, you can in a much simpler way:

```
y = ...

x = copy(x)
```


Perhaps you wanted to play with two different sets of parameters? That's what the `snapshot` and `reset` methods are for -- to allow you to easily switch between as many parameters as you want.

**Comment by sg-s** [comment]
To add on: if you add a `xolotl.cleanup` b/w the two models, everything will work because the binary is deleted and therefore will be rebuilt with the correct names.

**Comment by sg-s** [comment]
Finally, if you do want to have two different objects, here's how you do it:

```
x = ... (set up your model)

y = copy(x)

% make sure you update I_ext
y.I_ext = x.I_ext; 


```

now `x` and `y` correspond to the same model, but you have two copies of them to do with as you wish

**Comment by sg-s** [comment]
@alec-hoyland Somewhere in the documentation we need point out this behaviour, and steer users towards using the `copy` method

**Comment by luadam4c** [comment]
Yeah I think x.copy() would be important in the documentation. There are often times when we want to test out similar models and compare between them. Thanks for resolving this!

**Comment by alec-hoyland** [comment]
I'll write up the documentation tomorrow.
If you're not changing the structure of a model (e.g. adding new compartments or conductances) there's no need for multiple xolotl objects, since the `reset` and `snapshot` methods allow you to revert back to any state you want.

**Comment by alec-hoyland** [comment]
If you are changing the structure of models, then copy can be useful. Ordinarily I write a function or script to create each model though.
