### ISSUE TITLE
adaptive sampling demo fails because I don't have the `adaptive` class

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#482]
Where is the code for the class?

**Comment by sg-s** [comment]
mtools -- you need to git pull that

**Comment by sg-s** [comment]
![Screen Shot 2019-12-04 at 4 58 27 PM](https://user-images.githubusercontent.com/6005346/70185191-4f17af80-16b7-11ea-8673-f508aba12a55.png)

**Comment by alec-hoyland** [comment]
Ah, I found it -- I was pulling from my forked version of mtools.

**Comment by sg-s** [comment]
What's in your fork? send a PR if you think there is something that should be in mine

**Comment by alec-hoyland** [comment]
Usually I do.
I don't have anything in it right now that different. Clearly it's very stale.

On December 6, 2019 10:00:49 AM EST, Srinivas Gorur-Shandilya <notifications@github.com> wrote:
>What's in your fork? send a PR if you think there is something that
>should be in mine
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/sg-s/xolotl/issues/482#issuecomment-562605254

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
