### ISSUE TITLE
The how-tos and online tutorials need to be tested against too

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#496]
Something should read the file, strip out all the code, and run it to make sure it runs

**Comment by alec-hoyland** [comment]
This regular expression should grab all the MATLAB code in a markdown file: ````matlab([\s\S]*?)````

**Comment by alec-hoyland** [comment]
The regex approach was giving me too much trouble, so I wrote a matlab script instead.

https://github.com/sg-s/xolotl/blob/test-docs-code/%40xtest/testHowTos.m

This script will work under the circumstances that we

* always use \```matlab to begin code blocks and use \``` to end them
* don't put non-executable matlab code inside of those blocks

The main takeaway from this is that if we use this function, we have to move "output" to a new code block, using \``` to start and \``` to end.

**Comment by alec-hoyland** [comment]
One really easy fix is to just remove `matlab` in the code block declaration anytime we *don't* want that code run.

**Comment by sg-s** [comment]
Instead of which, why can't we strip out all the MATLAB code in the code blocks, combine them all, and run them? It will be the responsibility of the person writing the docs to make sure that the code in the code block runs when this is done

**Comment by sg-s** [comment]
What I mean to say it, all code should be executable code

**Comment by sg-s** [comment]
This is partially fixed in https://github.com/sg-s/xolotl/commit/28129fabe2100a6dc052b363d83368a2daa17ce7 

Right now, only the `how-to` folder is checked.
