### ISSUE TITLE
show() needs to work with synapses 

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#497]
The challenge with synapses is that only `s` is defined -- the synapse can implement whatever it wants to actually integrate. So we can't directly read out `tau_s` or `s_inf` because they may not even be defined.

**Comment by alec-hoyland** [comment]
Call a show method defined uniquely for each synapse class?

**Comment by sg-s** [comment]
I did something else -- I used the same architecture that exists for conductance for synapses. The actual C++ code is run, `s` is calculated, and `s_inf` and `tau_s` are inferred.
