### ISSUE TITLE
Conductances with instantaneous kinetics

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#499]
Some conductances have instantaneous kinetics, that is, if `m` is instantaneous then, instead of 

```
tau_m(V, Ca) * dm/dt = m_inf(V, Ca) - m(V, Ca, t)
``` 

being the equation-of-state, we have

```
m(V, Ca, t) = m_inf(V, Ca)
```

A real example can be found [here](https://journals.plos.org/ploscompbiol/article/file?type=supplementary&id=info:doi/10.1371/journal.pcbi.1005879.s001).

How do we go about integrating this conductance? My first guess would be to override the virtual definition `void conductance::integrate(double V, double Ca)` for any conductance that needs this, but maybe there is a better way?

**Comment by alec-hoyland** [comment]
https://github.com/sg-s/xolotl/blob/39fa25ac722d41e9b5baf541919eb7259fa785b6/c%2B%2B/conductances/soplata/CaT.hpp#L79

**Comment by alec-hoyland** [comment]
#501

**Comment by sg-s** [comment]
Like [this](https://github.com/sg-s/xolotl/blob/master/c%2B%2B/conductances/morris-lecar/CaCurrent.hpp)

Basically, you're going to define an integrate method that looks like:

```
void CaCurrent::integrate(double V, double Ca) {

    if (isnan(E)) {
        // update form container
        E = container->E_Ca;
    } else {
        // update to container
        container->E_Ca = E;
    }

    g = gbar*m_inf(V,Ca);

    container->i_Ca += getCurrent(V);
    
}

```

**Comment by sg-s** [comment]
@alec-hoyland There's way too much cruft in soplata/CaT...

**Comment by sg-s** [comment]
They way to do this correctly is in conductance::connect, to check if tau_m is 0, and if so, set an integer flag, so we can use a switch statement in conductance::integrate to modify the integrate step

This way you have to write 0 extra code for new conductances...this might be worth doing

**Comment by alec-hoyland** [comment]
I think that should work just fine. I will try my hand at this.

**Comment by sg-s** [comment]
never mind, already did this

**Comment by alec-hoyland** [comment]
Oops. #502
