### ISSUE TITLE
Package download ships with paths.cpplab, which breaks everything unless cache is rebuilt

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#520]
```
>> demo_clamp
Error using md5hash
*** md5[mex]: Cannot open file: [/Users/srinivas/GoogleDrive/code/xolotl/c++/compartment.hpp]

Error in cpplab (line 80)
self.cpp_hash = hashlib.md5hash(hpp_path,'File');

Error in xolotl/add (line 71)
obj = cpplab(obj_type, varargin{:});

Error in demo_clamp (line 10)
x.add('compartment','AB','A',0.0628);
 
```

@hananel-hazan

**Comment by sg-s** [comment]
@hananel-hazan 

1. Did you install xolotl using the package or using git?
2. Did you run `xolotl.rebuildCache()`?
3. Do the other demos work?

**Comment by sg-s** [comment]
This is because `paths.cpplab` is included in the package, and it should not be. Need to fix in package...

**Comment by Hananel-Hazan** [comment]
Thanks for replying 

Seems that the compiler is missing... I will install matlab on VM and get back to you

1. install the last version from here. 
https://github.com/sg-s/xolotl/releases/latest/

2. running `xolotl.rebuildCache()?` command  give the following output:
```
>> xolotl.rebuildCache()
Rebuilding cache, this may take a while...
D:\MATLAB
C:\Users\user\AppData\Local\Temp\Editor_vxdxq
D:\MATLAB\Add-Ons\Toolboxes\xolotl
D:\MATLAB\Add-Ons\Toolboxes\xolotl\Users\srinivas\GoogleDrive\code\puppeteer
D:\MATLAB\Add-Ons\Toolboxes\xolotl\Users\srinivas\GoogleDrive\code\cpplab
D:\MATLAB\Add-Ons\Toolboxes\xolotl\Users\srinivas\GoogleDrive\code\srinivas.gs_mtools
All DONE! Found 378 C++ files
```
3. Other demos in the 
Error using mex
No supported compiler was found. You can install the freely available MinGW-w64 C/C++ compiler; see Install MinGW-w64
Compiler. For more options, visit https://www.mathworks.com/support/compilers.

**Comment by sg-s** [comment]
OK, running `xolotl.rebuildCache` will fix your original issue. 

You now have a new one: you need a C++ compiler. Please see the quick start

https://xolotl.readthedocs.io/en/master/tutorials/start-here/

to see how to install a compiler

**Comment by Hananel-Hazan** [comment]
c++ compiler is now available 
When running the `demo_clamp` I got the following error:
```
>> demo_clamp
Unrecognized function or variable 'V'.

Error in demo_clamp (line 17)
actual_m_inf = NaN*V;
```

**Comment by sg-s** [comment]
Yeah, sorry, that's my bad. This is fixed in the latest release (mondrian)

https://github.com/sg-s/xolotl/releases

Or you can just copy the script and run it...

https://github.com/sg-s/xolotl/blob/master/examples/demo_clamp.m

**Comment by Hananel-Hazan** [comment]
the script works, thanks!

**Comment by sg-s** [comment]
Awesome, closing this for now. let me know if something else is not ok
