### ISSUE TITLE
Current units not consistent with output_type? 

### ISSUE THREAD

**Issue by JRS92** [sg-s/xolotl#533]
It seems that units change depending on which output type is used and this is confusing. 

A simple voltage clamp experiment involving a single compartment with a leak conductance. Clamped at 0 mV: 

```
x = xolotl;
x.add('compartment','HH','A',.01);
x.HH.add('Leak', 'gbar', 1);
x.t_end = 100; 
x.V_clamp = 0; 
x.closed_loop = false; 
output0 = x.integrate;
x.output_type = 1; 
output1 = x.integrate;
```

A) output0 contains an initial transient followed by steady state at 0.55 
B) output1.HH.I_clamp contains an initial transient followed by steady state at 0.55 
C) output1.HH.Leak.I contains steady state at at 55 (no transient)

Why the difference in magnitude A and B vs C? In a single compartment with one channel type, should not I_clamp be equal to capacitance current plus current through that channel?

**Comment by sg-s** [comment]
HI @JRS92, you're not comparing the same thing.

The outputs of `output0` and `output1.HH.I_clamp` are identical -- transient + steady state at 0.55

`output1.HH.Leak.I` contains the specific current density through that channel -- you will see that this value differs from the first by the area of the cell (.01) 

You're right in that the documentation does not say this -- it will be updated to reflect this behaviour

**Comment by sg-s** [comment]
As for the transient -- that's a numerical error (it's one time step long) and is kinda unavoidable.

**Comment by JRS92** [comment]
Ah okay, so one is current density while the other is strictly I. That makes sense, and would be helpful to mention in the documentation. Thanks!

**Comment by sg-s** [comment]
Docs have been updated to reflect this, thanks for the bug report!
