### ISSUE TITLE
Missing binaries for examples

### ISSUE THREAD

**Issue by neurologic** [sg-s/xolotl#549]
**System**
Mac OS Mojave
Matlab 2020b

**Steps taken to obtain error**
I followed the quickstart guide at https://xolotl.readthedocs.io/en/master/tutorials/start-here/
On the following step 

```xolotl.go_to_examples```
```demo_bursting_neuron```

I received the error below:

**Error**

```
Error using corelib.assert (line 28)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

download >>>> Could not download a pre-complied binary for this model. You will have to
manually compile yourself. You will need a configured C++ compiler for this.

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

Error in xolotl/download (line 42)
	corelib.assert(false,'Could not download a pre-complied binary for this model. You
        will have to manually compile yourself. You will need a configured C++ compiler
        for this.')

Error in demo_bursting_neuron (line 17)
	x.download;
```

**Other steps taken to try to fix**
I tried running ``` xolotl.cleanup ``` and ``` cpplab.rebuildCache ``` but the error persisted.

Thank you for your time and help!

**Comment by sg-s** [comment]
closing this issue for now -- please let me know if this does not fix it
