### ISSUE TITLE
package does not include List (which also conflicts with a builtin) and causes object display to fail

### ISSUE THREAD

**Issue by peterle041963** [sg-s/xolotl#550]
# Please go through the following steps before you file an issue that documents a problem or a potential bug and please check each item as you do so: 

- [x] I have read the [troubleshooting](https://xolotl.readthedocs.io/en/latest/troubleshooting.html) page
- [x] I have run `xolotl.cleanup` and my error persists
- [x] I have run `cpplab.rebuildCache` and my error persists
- [x] The built-in examples work

# Information

Please provide the following information:

## Operating System 
 Windows 10
## Output of "version" command in MATLAB
 '9.9.0.1570001 (R2020b) Update 4'
## Output of "mex.getCompilerConfigurations('C++')" in MATLAB
 CompilerConfiguration with properties:

             Name: 'MinGW64 Compiler (C++)'
     Manufacturer: 'GNU'
         Language: 'C++'
          Version: '6.3.0'
         Location: 'C:\ProgramData\MATLAB\SupportPackages\R2020b\3P.instrset\mingw_w64.instrset'
        ShortName: 'mingw64-g++'
         Priority: 'E'
          Details: [1×1 mex.CompilerConfigurationDetails]
       LinkerName: 'C:\ProgramData\MATLAB\SupportPackages\R2020b\3P.instrset\mingw_w64.instrset\bin\g++'
    LinkerVersion: ''
           MexOpt: 'C:\Users\peter\AppData\Roaming\MathWorks\MATLAB\R2020b\mex_C++_win64.xml'

# Bug reports

Please replace this section with:

### What you were trying to do (include code to reproduce error)
I was trying to run through the "your first neuron module" but kept on getting an error when adding a compartment.
### What you expected to happen
When I run x, I expected the prompt showing which compartments were successfully added.
### What actually happened
![image](https://user-images.githubusercontent.com/74978824/108261734-04eee280-7132-11eb-97ca-fecd7cabd6d4.png)

**Comment by sg-s** [comment]
hi, thanks for the detailed error report.

this is because your copy of mtools (a dependency) is out of date.

# if you installed via the package

oops, my bad. i'll have to build a new one

# installed using git/direct download

you need to update https://github.com/sg-s/srinivas.gs_mtools/

using git:

```
git pull
```

**Comment by sg-s** [comment]
OK, the problem has been identified -- the package is missing a dependency which needs to be added.

- In the short term, you can continue to use xolotl -- most things should work. The missing function will cause the display method to fail, so if you add `;` to all statements things should work
- if you want to hot-patch your installation, you can download the missing function [here](https://github.com/sg-s/srinivas.gs_mtools/blob/master/List.m) and put it somewhere in your path

**Comment by sg-s** [comment]
OK, i've made a new release that includes List, and should fix your problem. Please uninstall (using the add-on manager) and reinstall the new toolbox from here

https://github.com/sg-s/xolotl/releases/tag/v21.2.17

closing for now, feel free to re-open if this doesn't fix your problem
