### ISSUE TITLE
better tree display

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#56]
use these characters to  show a nice tree:

 ├──

and

└─

**Comment by sg-s** [comment]
this isn't going to work

**Comment by alec-hoyland** [comment]
I guess MATLAB really doesn't like those ASCII characters...

It has no problem when I use them in Atom and copy paste. But I doubt that
will help here.

Alec

**Comment by sg-s** [comment]
really? 

when I try 

```
disp('├──') 
```

from the command line, it works for me.

but when have the same code in a script, and call that script, MATLAB fucks it up. same for you?
