### ISSUE TITLE
Struggling with inhibitory synapses

### ISSUE THREAD

**Issue by AlexSonneborn** [sg-s/xolotl#578]
# Please go through the following steps before you file an issue that documents a problem or a potential bug and please check each item as you do so: 

- [X] I have read the [troubleshooting](https://xolotl.readthedocs.io/en/latest/troubleshooting.html) page
- [X] I have run `xolotl.cleanup` and my error persists
- [X] I have run `cpplab.rebuildCache` and my error persists
- [X] The built-in examples work

# Information

Please provide the following information:

## Operating System 
Windows 10
## Output of "version" command in MATLAB
'9.11.0.1769968 (R2021b)'
## Output of "mex.getCompilerConfigurations('C++')" in MATLAB

ans = 

  CompilerConfiguration with properties:

             Name: 'MinGW64 Compiler (C++)'
     Manufacturer: 'GNU'
         Language: 'C++'
          Version: '6.3.0'
         Location: 'C:\ProgramData\MATLAB\SupportPackages\R2021b\3P.instrset\mingw_w64.instrset'
        ShortName: 'mingw64-g++'
         Priority: 'E'
          Details: [1×1 mex.CompilerConfigurationDetails]
       LinkerName: 'C:\ProgramData\MATLAB\SupportPackages\R2021b\3P.instrset\mingw_w64.instrset\bin\g++'
    LinkerVersion: ''
           MexOpt: 'C:\Users\sonnebor\AppData\Roaming\MathWorks\MATLAB\R2021b\mex_C++_win64.xml'

# Bug reports

Please replace this section with:

### What you were trying to do (include code to reproduce error)
I am trying to make an inhibitory synapse
### What you expected to happen
I expected whenever the inhibitory cell fired to have a brief hyperpolarization in my mPFC pyramidal cell (below).
### What actually happened
I pasted the error and my code below. The 5th to last line is the one that is causing the issue. If I just comment this line out, everything works fine. 

```
Error using mex
C:\Users\sonnebor\AppData\Local\Temp\1\mex_2263249688272427_58116\X_c76349b260203eda05b19936eaa74757.obj:X_c76349b260203eda05b19936eaa74757.cpp:(.rdata$_ZTV10Inhibitory[_ZTV10Inhibitory]+0x38):
undefined reference to `Inhibitory::getCurrent(double)'
collect2.exe: error: ld returned 1 exit status


Error in xolotl/compile (line 64)
	mex('-silent',ipath,mexBridge_name,'-outdir',filelib.cachePath('xolotl'))

Error in xolotl/integrate (line 113)
	self.compile;

Error in xolotl/plot (line 150)
[V, Ca, ~, currents] = self.integrate;

Error in FirstXolotl (line 35)
x.plot
```

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

```
x = xolotl;

% Adding different neurons
x.add('compartment','CLA','A', .05);
x.add('compartment','mPFCinter','A', .025);
x.add('compartment','mPFCPyr1','A', .05);

x.approx_channels = 0;
x.stochastic_channels = 0;

% Adding in 
x.CLA.add('liu/NaV', 'gbar', 1000, 'E', 30);
x.CLA.add('liu/Kd', 'gbar', 300, 'E', -80);
x.CLA.add('turrigiano/ASlow');
x.CLA.add('traub/Kahp');
x.CLA.add('hill/HCurrent');
x.CLA.add('Leak', 'gbar', .1);

x.mPFCinter.add('liu/NaV', 'gbar', 1000, 'E', 30);
x.mPFCinter.add('liu/Kd', 'gbar', 300, 'E', -70);
x.mPFCinter.add('Leak', 'gbar', .1);

x.mPFCPyr1.add('liu/NaV', 'gbar', 1000, 'E', 30);
x.mPFCPyr1.add('liu/Kd', 'gbar', 300, 'E', -80);
x.mPFCPyr1.add('Leak', 'gbar', .1);
x.mPFCPyr1.add('hill/HCurrent');

% Adding some synapses between neurons
x.connect('CLA','mPFCinter','borgers/AMPA', 'gmax', 30);
x.connect('CLA','mPFCinter','borgers/NMDA', 'gmax', 30);
x.connect('mPFCinter','mPFCPyr1','cymbalyuk/Inhibitory','gmax',40);

x.t_end = 1000; %ms
x.I_ext = [randn(x.t_end/x.sim_dt,1) randn(x.t_end/x.sim_dt,1) randn(x.t_end/x.sim_dt,1)];
x.plot

xlim([0 1])
```

**Comment by sg-s** [comment]
hello, are you trying to make your own custom synapse? 

if so, please also paste in the C++ code in your .hpp file. 

if you're using a built-in synapse, please point to the problematic synapse

**Comment by rolsonjames94** [comment]
I have also been having this problem, thank you :)

**Comment by AlexSonneborn** [comment]
Thanks! I think I can just do this for the soplata GABAergic one as well? It is line 42 in that script.

**Comment by sg-s** [comment]
oof, you are absolutely right, yes, you can. I'll fix those in other synapses where I can find them and push this patch

**Comment by sg-s** [comment]
Yes, please see:

https://xolotl.readthedocs.io/en/master/how-to/inject-current/#inject-a-time-varying-current-into-a-compartment
