### ISSUE TITLE
xolotl x.fit issue

### ISSUE THREAD

**Issue by smbaca** [sg-s/xolotl#588]
# Please go through the following steps before you file an issue that documents a problem or a potential bug and please check each item as you do so: 

X I have read the [troubleshooting](https://xolotl.readthedocs.io/en/latest/troubleshooting.html) page
X I have run `xolotl.cleanup` and my error persists
X I have run `cpplab.rebuildCache` and my error persists
- The built-in examples work

# Information

Please provide the following information:

## Operating System 
Windows 11

## Output of "version" command in MATLAB
2022B - most recent
9.13.0.2080170 (R2022) Update 1
GO Toolbox 4.8
O Toolbox 9.4
PC Toolbox 7.7
SS Toolbox 9.1
## Output of "mex.getCompilerConfigurations('C++')" in MATLAB
Uses windows compiler. Works

# Bug reports

Please replace this section with:

We installed xolotl on a new Windows 11 machine with latest version of MATLAB.
xolotl.run_all_tests reports an error. In tracking it down, I think it is a change in the optimization toolboxes. x.fit throws the error. The run_all_tests works fine on a Windows 10 machine with the older Toolboxes.

### What you expected to happen
Expected all tests to run without issue.

### What actually happened
See screen shot of error. In testing other demos we found that they run ok and the conductances can be compiled. So we think the issue is limited to a change in one of the toolbox functions called when using p.fit in the run_all_tests call.

demo_xfit also throws the same error.

![IMG_4724](https://user-images.githubusercontent.com/2848274/200396396-b602ee46-67b2-4fce-8ce6-5bb51ac4c929.jpg)

**Comment by smbaca** [comment]
Ok, bug resolved. I went searching online and several people said to either reshape the vector or to make sure the Statistics Toolbox was installed. I installed what is now the Statistics and Machine Learning Toolbox and re-ran the code and everything works again.

**Comment by sg-s** [comment]
excellent, yes, nanmean is needed

closing for now
