### ISSUE TITLE
pointless warnings when compiling on linux

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#59]

**Comment by alec-hoyland** [comment]
Seems more complicated to fix than necessary...

https://www.mathworks.com/matlabcentral/answers/92145-how-do-i-disable-the-unsupported-compiler-warning-message-generated-by-the-mex-command-in-matlab-7-1

**Comment by sg-s** [comment]
ok, then use this simple workaround:

```
warning('off')
mex(...)
warning('on')
```
