### ISSUE TITLE
xolotl won't run on M3 Mac

### ISSUE THREAD

**Issue by smbaca** [sg-s/xolotl#591]
# Please go through the following steps before you file an issue that documents a problem or a potential bug and please check each item as you do so: 

- [ ] I have read the [troubleshooting](https://xolotl.readthedocs.io/en/latest/troubleshooting.html) page
- [ ] I have run `xolotl.cleanup` and my error persists
- [ ] I have run `cpplab.rebuildCache` and my error persists
- [ ] The built-in examples work

# Information

Please provide the following information:

## Operating System 
Sonoma 14.5 Mac OS on M3 
## Output of "version" command in MATLAB
'24.1.0.2628055 (R2024a) Update 4'
## Output of "mex.getCompilerConfigurations('C++')" in MATLAB
 CompilerConfiguration with properties:

             Name: 'Xcode Clang++'
     Manufacturer: 'Apple'
         Language: 'C++'
          Version: '15.0.0'
         Location: '/Applications/Xcode.app/Contents/Developer'
        ShortName: 'Clang++'
         Priority: 'A'
          Details: [1×1 mex.CompilerConfigurationDetails]
       LinkerName: '/usr/bin/xcrun -sdk macosx14.5 clang++'
    LinkerVersion: ''
           MexOpt: '/Users/smbaca/Library/Application Support/MathWorks/MATLAB/R2024a/mex_C++_maca64.xml'

# Bug reports
So, we are trying to run xolotl on the new silicon Mac M3 chip. When I load up our usual setup that works on Macs and pcs I get the following error:

```matlab
Error using assert
md5hash does not point to compiled binary

Error in hashlib.test (line 10)
assert(strcmpi(['.' mexext],ext),'md5hash does not point to compiled binary')

Error in xolotl.run_all_tests (line 37)
hashlib.test()

Error in setup_xolotl_beenhakker_class (line 52)
xolotl.run_all_tests % tests xolotl installed ok
```

Is there a hash file for the M3 that will work? I am happy to compile or try to troubleshoot. More and more of the kids are using M1-M3 Macs in the class, so we would like to be able to make xolotl and the tutorials we have designed available for their personal use vs sharing systems.

**Comment by sg-s** [comment]
This is going to be almost impossible for me to fix be cause I don't have access to matlab anymore. Sorry!

**Comment by smbaca** [comment]
I'm happy to give you remote access to the M3 system if you want to give it a go. If not is there any general advice on how to generate the necessary files for Xolotl to run?

**Comment by smbaca** [comment]
Ok so I just mex compiled the hash.c file and now it looks like everything is up and running on the M3. I can send the file if interested.

**Comment by sg-s** [comment]
Can you please send a pull request? I suspected this was the case.

**Comment by sg-s** [comment]
@smbaca i have identified the exact cause. 

[this line in mtools/hashlib](https://github.com/sg-s/srinivas.gs_mtools/blob/a520e4a787e39c473503b9f2b31d39d50e1ea51c/src/%2Bhashlib/test.m#L10) throws an error because it expects the compiled md5hash binary to have the extension `mexmaca64`. See this page:

https://www.mathworks.com/help/matlab/ref/mexext.html

for extensions on different platforms. 

It does not, because this C program has never been compiled on a mac arm platform before. 

to fix this, you need to modify that file (in that repo).

**Comment by smbaca** [comment]
Yes I compiled the file in question and will upload. There was also a regular warning about not using a scalar and I think I corrected that and will send what I did once I get to my computer.Sent from my iPhoneOn Jun 26, 2024, at 9:14 PM, Srinivas Gorur-Shandilya ***@***.***> wrote:﻿
@smbaca i have identified the exact cause.
this line in mtools/hashlib throws an error because it expects the compiled md5hash binary to have the extension mexmaca64. See this page:
https://www.mathworks.com/help/matlab/ref/mexext.html
for extensions on different platforms.
It does not, because this C program has never been compiled on a mac arm platform before.
to fix this, you need to modify that file (in that repo).

**Comment by sg-s** [comment]
ok, thank you! please open a PR on this repo:

https://github.com/sg-s/srinivas.gs_mtools

**Comment by sg-s** [comment]
i'm closing this issue because you fixed this in mtools
