### ISSUE TITLE
image thread

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#6]

**Comment by sg-s** [comment]
![screen shot 2017-09-21 at 3 02 46 pm](https://user-images.githubusercontent.com/6005346/30713658-ff96faf4-9edd-11e7-9db1-a2ca4f2f0567.png)

**Comment by sg-s** [comment]
![hero](https://user-images.githubusercontent.com/6005346/30719217-a1e8d54a-9ef0-11e7-8889-c284ac13163e.png)

**Comment by sg-s** [comment]
![test mov](https://user-images.githubusercontent.com/6005346/30785272-aef9fb44-a132-11e7-84a6-25fd8e58470a.gif)

**Comment by sg-s** [comment]
<img width="992" alt="xolotl-header" src="https://user-images.githubusercontent.com/6005346/41205222-30b6f3d4-6cbd-11e8-983b-9125585d629a.png">

**Comment by alec-hoyland** [comment]
![xolotl_is_easy](https://user-images.githubusercontent.com/30243182/42067394-0801376e-7b14-11e8-8eb3-b20b64ffaf9f.png)

**Comment by alec-hoyland** [comment]
![xolotl_benchmark](https://user-images.githubusercontent.com/30243182/42105769-9c1c407a-7b9f-11e8-86fb-8fc56eac9ff6.png)

**Comment by sg-s** [comment]
![untitled](https://user-images.githubusercontent.com/6005346/44669694-24e53580-aa10-11e8-9bd0-5b0378d33342.png)

**Comment by sg-s** [comment]
![untitled](https://user-images.githubusercontent.com/6005346/44669774-6544b380-aa10-11e8-86e8-7bea1b2ad90b.png)

**Comment by alec-hoyland** [comment]
![manipulate](https://user-images.githubusercontent.com/30243182/49181191-bb353a00-f324-11e8-992c-9171209a7149.gif)

**Comment by alec-hoyland** [comment]
![fig1](https://www.frontiersin.org/files/Articles/419941/fninf-12-00087-HTML/image_m/fninf-12-00087-g001.jpg)

**Comment by alec-hoyland** [comment]
![fig2](https://www.frontiersin.org/files/Articles/419941/fninf-12-00087-HTML/image_m/fninf-12-00087-g002.jpg)

**Comment by alec-hoyland** [comment]
![fig3](https://www.frontiersin.org/files/Articles/419941/fninf-12-00087-HTML/image_m/fninf-12-00087-g003.jpg)

**Comment by alec-hoyland** [comment]
![fig4](https://www.frontiersin.org/files/Articles/419941/fninf-12-00087-HTML/image_m/fninf-12-00087-g004.jpg)

**Comment by alec-hoyland** [comment]
![fig5](https://www.frontiersin.org/files/Articles/419941/fninf-12-00087-HTML/image_m/fninf-12-00087-g005.jpg)

**Comment by alec-hoyland** [comment]
![fig6](https://www.frontiersin.org/files/Articles/419941/fninf-12-00087-HTML/image_m/fninf-12-00087-g006.jpg)

**Comment by alec-hoyland** [comment]
![fig7](https://www.frontiersin.org/files/Articles/419941/fninf-12-00087-HTML/image_m/fninf-12-00087-g007.jpg)

**Comment by alec-hoyland** [comment]
![xolotl](https://user-images.githubusercontent.com/30243182/49184986-b83f4700-f32e-11e8-9899-cd7e20e95fa9.gif)

**Comment by sg-s** [comment]
![bursting_neuron](https://user-images.githubusercontent.com/6005346/49969670-1c4d3800-fef7-11e8-97ff-8350cc487a7b.png)

**Comment by sg-s** [comment]
![screen shot 2018-12-13 at 4 59 23 pm](https://user-images.githubusercontent.com/6005346/49970181-82868a80-fef8-11e8-8887-cad414a6dcb5.png)

**Comment by sg-s** [comment]
![screen shot 2018-12-14 at 10 46 27 am](https://user-images.githubusercontent.com/6005346/50012791-90d2b600-ff8d-11e8-87c3-b927bf462441.png)

**Comment by sg-s** [comment]
![screen shot 2018-12-14 at 10 50 59 am](https://user-images.githubusercontent.com/6005346/50013064-2c642680-ff8e-11e8-8089-846b5900644e.png)

**Comment by sg-s** [comment]
![screen shot 2018-12-14 at 10 58 33 am](https://user-images.githubusercontent.com/6005346/50013473-3c303a80-ff8f-11e8-88f7-6afaa16826de.png)

**Comment by sg-s** [comment]
<img width="1113" alt="screen shot 2018-12-15 at 14 08 47" src="https://user-images.githubusercontent.com/6005346/50046554-1714f800-0073-11e9-9b1f-f136baff7976.png">

**Comment by sg-s** [comment]
<img width="608" alt="speed" src="https://user-images.githubusercontent.com/6005346/50499683-9c0bf400-0a19-11e9-9375-92a1fdefa2fc.png">

**Comment by sg-s** [comment]
<img width="1224" alt="screen shot 2018-12-27 at 21 01 49" src="https://user-images.githubusercontent.com/6005346/50499821-b4304300-0a1a-11e9-8c0a-0eed1ea5f666.png">

**Comment by sg-s** [comment]
<img width="1409" alt="screen shot 2018-12-27 at 21 03 29" src="https://user-images.githubusercontent.com/6005346/50499847-e3df4b00-0a1a-11e9-8aba-b3be57c3e784.png">

**Comment by sg-s** [comment]
<img width="1095" alt="screen shot 2018-12-28 at 09 32 54" src="https://user-images.githubusercontent.com/6005346/50518461-bd092f00-0a83-11e9-8869-cbe39ffc00ee.png">

**Comment by sg-s** [comment]
![untitled](https://user-images.githubusercontent.com/6005346/50520183-e11d3e00-0a8c-11e9-8f87-74eb6a98e672.png)

**Comment by sg-s** [comment]
<img width="1312" alt="screen shot 2018-12-28 at 10 41 04" src="https://user-images.githubusercontent.com/6005346/50520224-1c1f7180-0a8d-11e9-9825-d42869338d33.png">

**Comment by sg-s** [comment]
<img width="1179" alt="screen shot 2018-12-28 at 10 44 19" src="https://user-images.githubusercontent.com/6005346/50520304-951ec900-0a8d-11e9-8ec1-88398062da2c.png">

**Comment by sg-s** [comment]
<img width="823" alt="screen shot 2018-12-28 at 10 48 52" src="https://user-images.githubusercontent.com/6005346/50520444-6bb26d00-0a8e-11e9-82ba-128f08d28d30.png">

**Comment by sg-s** [comment]
<img width="969" alt="screen shot 2018-12-28 at 11 06 39" src="https://user-images.githubusercontent.com/6005346/50520860-ac12ea80-0a90-11e9-94ee-4f1e348e83bb.png">

**Comment by sg-s** [comment]
<img width="504" alt="screen shot 2019-01-10 at 11 10 05" src="https://user-images.githubusercontent.com/6005346/50981138-5135b600-14c8-11e9-9be7-b01203716a10.png">

**Comment by sg-s** [comment]
![manipulate-small-2](https://user-images.githubusercontent.com/6005346/57262966-9b751100-703c-11e9-890f-3808062e60d9.gif)

**Comment by sg-s** [comment]
![Screen Shot 2019-07-31 at 3 54 34 PM](https://user-images.githubusercontent.com/6005346/62243615-a88b6d00-b3ab-11e9-94a8-828cb41acc60.png)

**Comment by alec-hoyland** [comment]
![demo_finite_size](https://user-images.githubusercontent.com/30243182/62395704-0c926a80-b53f-11e9-8769-fad0d963e9ec.png)

demo_finite_size

**Comment by alec-hoyland** [comment]
![shuffled_prinz_model](https://user-images.githubusercontent.com/30243182/62645076-82b91780-b919-11e9-86fe-4b01b8c9d885.png)
 shuffled prinz model

**Comment by alec-hoyland** [comment]
![demo_xfit](https://user-images.githubusercontent.com/30243182/62645332-ff4bf600-b919-11e9-8660-b6331717d40d.png)

**Comment by alec-hoyland** [comment]
![demo_adaptive_sampling](https://user-images.githubusercontent.com/30243182/70347267-31b92180-182e-11ea-91f1-af4df6d953c0.png)

**Comment by alec-hoyland** [comment]
![figure_param_opt_benchmark](https://user-images.githubusercontent.com/30243182/70347287-3aa9f300-182e-11ea-9355-47fc84bedb26.png)

Benchmark of parameter optimization algorithms. (a) Cost over time for the cost func-
  tion measuring burst frequency, mean number of spikes per burst, and duty cycle, as a function of
  real time. A cost of zero indicates a model that satisfies all constraints. Colors indicate different
  algorithms used. Particle swarm and genetic algorithm are stochastic and were simulated 100 times
  each (multiple trajectories plotted). (b) Proportion of models reaching a cost of zero during optimization
  as a function of the optimization time. (c) Waveform of model before optimization (black)
  and waveform after particle swarm optimization with zero cost (red). (d) Depiction of the conductance parameters in base-10 logarithmic units for the model before optimization (transparent) and after optimization depicted in (c).

**Comment by sg-s** [comment]
![Screen Shot 2020-03-20 at 12 08 17 PM](https://user-images.githubusercontent.com/6005346/77182736-97f74680-6aa3-11ea-9077-fcedd122e2f6.png)

**Comment by sg-s** [comment]
![Screen Shot 2020-03-20 at 12 12 11 PM](https://user-images.githubusercontent.com/6005346/77183001-0c31ea00-6aa4-11ea-969e-3a6dd274ebda.png)

**Comment by sg-s** [comment]
![fry](https://user-images.githubusercontent.com/6005346/93216395-ad3ced00-f735-11ea-8512-5915c4b70d87.gif)

**Comment by sg-s** [comment]
![hero](https://user-images.githubusercontent.com/6005346/99264565-9fb3ea00-27ee-11eb-8800-64dea9f563e4.gif)

**Comment by sg-s** [comment]
![Screen Shot 2020-12-11 at 11 20 19 AM](https://user-images.githubusercontent.com/6005346/101928009-18665600-3ba3-11eb-95e6-9c7606e5f42d.png)

**Comment by sg-s** [comment]
![Screen Shot 2021-02-25 at 4 42 39 PM](https://user-images.githubusercontent.com/6005346/109223411-8a087600-7788-11eb-8f2a-c2b5dac8e01c.png)

**Comment by sg-s** [comment]
![Screen Shot 2021-02-25 at 5 04 08 PM](https://user-images.githubusercontent.com/6005346/109225710-a3f78800-778b-11eb-9a32-094f8b0b6068.png)

**Comment by sg-s** [comment]
![1](https://user-images.githubusercontent.com/6005346/127376671-4e8686d2-8063-4a5e-bad2-d913897cff0e.jpg)
