### ISSUE TITLE
if we provide dt to conductance constructors, there may be a speedup

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#63]
the idea is that we can cache exp(-dt/tau) for all values of V, and not perform an exponentiation over and over.

need to check if that's actually the rate limiting step

**Comment by sg-s** [comment]
looks like ~30% of the time is spend evaluating exp()

**Comment by alec-hoyland** [comment]
Would this only provide a speedup under the conditions that `tau` is
constant? Or can you cache for sufficient values of `tau` down to a
precision of `dt` that it would be worth it?

**Comment by sg-s** [comment]
you'd find all values of tau and cache that -- see [this example](https://github.com/sg-s/xolotl/blob/master/c%2B%2B/conductances/prinz-fast/NaV.hpp#L30)
