### ISSUE TITLE
Manipulating electrical synapses leads to strange and counter-intuitive behavior which is nevertheless correct

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#96]
# Steps to elicit:

1. Manipulate an object with an reciprocal electrical synapse (call these syn1 and syn2)
2. that has been created using `x.connect()`
3. Change synapse 1

# The problem

In reality, both synapse 1 and 2 change together, because they are the actually the same object. However, this is not reflected in `manipulate`

**Comment by alec-hoyland** [comment]
This is not necessarily bad. For example, this is how a model of rectifying
electrical synapses would work.
