### ISSUE TITLE
List of papers to include gating functions from

### ISSUE THREAD

**Issue by sg-s** [sg-s/xolotl#98]
- [x] Dethier...Sepulchre 2015
- [x] Brookings ... Marder 2014
- [x] Caplan 2014
- [x] Kispersky 2012
- [x] Drion 2011
- [ ] Taylor 2004
- [x] Soto-Trevino 2005
- [x] Prinz (J Neuro) 2003
- [x] Goldman 2001
- [ ] Soto-Trevino 201
- [x] Nadim 1999
- [ ] Manor 1999
- [ ] Golowasch 1999
- [x] Nadim 1998
- [ ] Weimann (J Neuro) 1997
- [x] Sharp 1993
- [ ] Epstein 1990
- [ ] Golowash & marder 1992
- [ ] Bucholtz 1992
- [x] [Rodriguez _et al._ 2013](http://www.jneurosci.org/content/33/46/18047.short)

**Comment by alec-hoyland** [comment]
I've started on Buchholtz 1992.

**Comment by alec-hoyland** [comment]
- [ ] [Rodriguez _et al._ 2013](http://www.jneurosci.org/content/33/46/18047.short)

**Comment by sg-s** [comment]
nice find, i'll add it to the list at the head of this thread

**Comment by alec-hoyland** [comment]
I've gotten through most of the readily-comprehensible papers (the ones with tables).

**Comment by sg-s** [comment]
and give up on the incomprehensible ones -- we want there to be a lot of papers, but there's nothing special about those ones.
